using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace zeebregtsCs
{
    public static class get_netnr
    {
        private static string[] _010 = { "010","Bergschenhoek", "Berkel en Rodenrijs", "Bleiswijk", "Botlek", "Capelle aan den Ijssel", "Hoogvliet", "Maasland", "Maassluis", "Albrands", "Vlaardingen", "Vondelingenplaat", "Pernis", "Poortugaal", "Rhoon", "Rotterdam", "Schiedam" };
        private static string[] _0111 = { "0111", "Burgh Haamstede", "Bruinisse", "Brouwershaven", "Dreischor", "Ellemeet", "Noordgouwe", "Noordwelle", "Nieuwerkerk", "Ouwerkerk", "Serooskerke", "Sirjansland", "Scharendijke", "Zonnemaire", "Zierikzee", "Kerkwerve", "Oosterland", "Renesse" };
        private static string[] _0113 = { "0113", "Baarland", "Borssele", "Driewegen", "Geersdijk", "'s-Heer Arendskerke", "'s-Heer Abtskerke", "Hansweert", "Hoedekenskerke", "'s-Heer Hendrikskinderen", "Heinkenszand", "'s-Heerenhoek", "Kamperland", "Krabbendijke", "Kortgene", "Kruiningen", "Nieuwdorp", "Nisse", "Rilland", "Wilhelminadorp", "Wemeldinge", "Wolphaartsdijk", "Waarde", "Wissenkerke", "Verseke", "Colijnsplaat", "Ellewoutsdijk", "'s-Gravenpolder", "Goes", "Kats", "Kapelle", "Kloetinge", "Kattendijke", "Kwadendamme", "Lewedorp", "Oostdijk", "Oudelande", "Ovezande", "Schore" };
        private static string[] _0114 = { "0114", "hengstdijk", "heikant", "hulst", "sint jansteen", "kapellebrug", "kuitaart", "koewacht", "nieuw namen", "ossenisse", "terhole", "vogelwaarde", "walsoorden", "clinge", "graauw", "kloosterzande", "lamswaarde" };
        private static string[] _0115 = { "0115", "axel", "hoek", "philippine", "sluiskil", "spui", "sas van gent", "terneuzen", "westdorpe", "zuiddorpe", "zaamslag", "biervliet", "overslag" };
        private static string[] _0117 = { "0117", "aardenburg", "breskens", "eede", "groede", "hoofdplaat", "sint kruis", "nieuwvliet", "oostburg", "sluis", "waterlandkerkje", "ijzendijke", "zuidzande", "cadzand", "retranchement", "schoondijke" };
        private static string[] _0118 = { "0118", "aagtekerke", "arnemuiden", "biggekerke", "domburg", "grijpskerke", "meliskerke", "nieuw en sint joosland", "oostkapelle", "ritthem", "serooskerke", "veere", "vlissingen", "vrouwenpolder", "westkapelle", "zoutelande", "gapinge", "koudekerke", "middelburg", "oost-souburg" };
        private static string[] _013 = { "013", "alphen", "baarle nassau", "biest houtakker", "biezenmortel", "berkel-enschot", "diessen", "de moer", "esbeek", "haghorst", "hooge mierde", "heukelom", "hulsel", "hilvarenbeek", "lage mierde", "oost west en middelbeers", "riel", " ulicoten", "udenhout", "castelre", "goirle", "moergestel", "oisterwijk", "tilburg" };
        private static string[] _015 = { "015", "delfgauw", "den hoorn", "nootdorp", "pijnacker", "schipluiden", "delft" };
        private static string[] _0161 = { "0161", "bavel", "bavel", "dorst", "gilze", "hulten", "rijen", "chaam", "molenschot" };
        private static string[] _0162 = { "0162", "dongen", "'s gravenmoer", "geertruidenberg", "hank", "den hout", "oosteind", "oosterhout", "raamsdonksveer", "drimmelen", "made", "raamsdonk" };
        private static string[] _0164 = { "0164", "huijbergen", "hoogerheide", "halsteren", "lepelstraat", "ossendrecht", "putte", "woensdrecht", "bergen op zoom" };
        private static string[] _0165 = { "0165", "hoeven", "nispen", "oudenbosch", "oud gastel", "rucphen", "standdaarbuiten", "sprundel", "schijf", "sint willebrord", "wouw", "wouwse plantage", "zegge", "bosschenhoofd", "heerle", "moerstraten", "roosendaal", "stampersgat" };
        private static string[] _0166 = { "0166", "sint annaland", "sint maartensdijk", "oud vossemeer", "poortvliet", "tholen", "scherpenisse", "stavenisse" };
        private static string[] _0167 = { "0167", "de heen", "nieuw vossemeer", "dinteloord", "kruisland", "sint philipsland", "steenbergen" };
        private static string[] _0168 = { "0168", "fijnaart", "heijningen", "hooge zwaluwe", "langeweg", "lage zwaluwe", "moerdijk", "oudemolen", "willemstad", "zevenbergschen hoek", "zevenbergschen hoek dri", "zevenbergen", "klundert" };
        private static string[] _0172 = { "0172", "aarlanderveen", "alphen aan den rijn", "bodegraven", "boskoop", "burgerveen", "hazerswoude dorp", "leimuiderbrug", "nieuwkoop", "noorden", "nieuwveen", "rijnsaterwoude", "ter aar", "woubrugge", "woerdense verlaat", "zevenhoven", "zwammerdam", "leimuiden" };
        private static string[] _0174 = { "0174", "s-gravenzande", "hoek van holland", "honselersdijk", "monster", "maasdijk", "naaldwijk", "ter heijde", "wateringen", "kwintsheul", "de lier", "poeldijk" };
        private static string[] _0180 = { "0180", "barendrecht", "krimpen aan den ijssel", "nieuwerkerk ad ijssel", "ouderkerk aan den ijssel", "zevenhuizen", "krimpen aan de lek", "lekkerkerk", "ridderkerk" };
        private static string[] _0181 = { "0181", "abbenbroek", "brielle", "europoort rotterdam", "geervliet", "hekelingen", "heenvliet", "hellevoetsluis", "oostvoorne", "oudenhoorn", "rockanje", "rozenburg", "simonshaven", "tinte", "vierpolders", "zuidland", "zwartewaal", "maasvlakte rotterdam", "spijkenisse" };
        private static string[] _0182 = { "0182", "ammerstol", "bergambacht", "berkenwoude", "gouda", "haastrecht", "hekendorp", "moordrecht", "polsbroek", "reeuwijk", "schoonhoven", "stolwijk", "vlist", "waddinxveen", "gouderak" };
        private static string[] _0183 = { "0183", "andel", "arkel", "ameide", "almkerk", "giessen", "goudriaan", "gorinchem", "hoogblokland", "hoornaar", "kedichem", "meerkerk", "nieuwendijk", "noordeloos", "nieuwland", "schelluinen", "spijk gem lingewaal", "sleeuwijk", "tienhoven", "uitwijk", "vuren", "woudrichem", "waardhuizen", "werkendam", "dalem", "rijswijk" };
        private static string[] _0184 = { "0184", "bleskensgraaf", "hardinxveld giessendam", "nieuw lekkerland", "nieuwpoort", "oud alblas", "ottoland", "sliedrecht", "streefkerk", "waal", "wijngaarden", "brandwijk", "giessenburg", "groot ammers", "langerak", "molenaarsgraaf" };
        private static string[] _0186 = { "0186", "heinenoord", "mijnsheerenland", "nieuw beijerland", "numansdorp", "oud beijerland", "piershil", "westmaas", "zuid-beijerland", "goudswaard", "klaaswaal" };
        private static string[] _0187 = { "0187", "achthuizen", "herkingen", "melissant", "nieuwe tonge", "ouddorp", "oude-tonge", "ooltgensplaat", "stellendam", "sommelsdijk", "den bommel", "dirksland", "goedereede", "middelharnis", "stad aan 't haringvliet" };
        private static string[] _020 = { "020", "amsterdam", "amsterdam zuidoost", "amstelveen", "badhoevedorp", "broek in waterland", "diemen", "ilpendam", "landsmeer", "ouderkerk aan de amstel", "oude meer", "uitdam", "watergang", "zuiderwoude", "zwanenburg", "duivendrecht", "halfweg", "den ilp", "luchthaven schiphol", "schiphol-rijk", "schiphol" };
        private static string[] _0222 = { "0222", "de cocksdorp", "den hoorn texel", "de koog", "oudeschild", "texel", "de waal", "den burg", "oosterend" };
        private static string[] _0223 = { "0223", "anna paulowna", "breezand", "den helder" };
        private static string[] _0224 = { "0224", "kolhorn", "lutjewinkel", "sint maartensbrug", "oudesluis", "schagerbrug", "schagen", "winkel", "wieringerwaard", "'t zand", "barsingerhorn", "callantsoog", "dirkshorn", "sint maarten", "sint maartensvlotbrug" };
        private static string[] _0226 = { "0226", "burgerbrug", "broek op langedijk", "hensbroek", "hoogwoud", "nieuwe niedorp", "noord-scharwoude", "obdam", "oude niedorp", "oudkarspel", "spanbroek", "'t veld", "waarland", "warmenhuizen", "zuid-scharwoude", "zijdewind", "opmeer", "petten", "tuitjenhorn" };
        private static string[] _0227 = { "0227", "hippolytushoef", "medemblik", "middenmeer", "den oever", "opperdoes", "slootdorp", "twisk", "westerland", "wieringerwerf", "kreileroord" };
        private static string[] _0228 = { "0228", "andijk", "bovenkarspel", "enkhuizen", "hem", "hoogkarspel", "lutjebroek", "venhuizen", "wervershoof", "westwoud", "zwaagdijk", "grootebroek" };
        private static string[] _0229 = { "0229", "abbekerk", "avenhorn", "aartswoud", "benningbroek", "berkhout", "de goorn", "hauwert", "hoorn", "lambertschaag", "midwoud", "nibbixwoud", "oostwoud", "oosterblokker", "oosterleek", "oudendijk", "schellinkhout", "spierdijk", "sijbekarspel", "wijdenes", "de weere", "wognum", "zuidermeer", "zwaag", "blokker", "scharwoude" };
        private static string[] _023 = { "023", "aerdenhout", "bennebroek", "bloemendaal", "boesingheliede", "cruquius", "hoofddorp", "haarlem", "haarlemmerliede", "heemstede", "lijnden", "overveen", "santpoort-zuid", "spaarndam", "velserbroek", "vogelenzang", "vijfhuizen", "zandvoort", "zwaanshoek", "bentveld", "spaarndam west", "santpoort-noord" };
        private static string[] _024 = { "024", "balgoij", "berg en dal", "beuningen", "erlecom", "groesbeek", "heumen", "heilig landstichting", "leuth", "lent", "middelaar", "molenhoek", "mook", "nederasselt", "nijmegen", "oosterhout gem nijmegen", "ooij", "overasselt", "persingen", "ubbergen", "wijchen", "weurt", "beek ubbergen", "leur", "malden", "plasmolen" };
        private static string[] _0251 = { "0251", "akersloot", "beverwijk", "heemskerk", "uitgeest", "velsen-noord", "wijk aan zee", "castricum" };
        private static string[] _0252 = { "0252", "abbenes", "buitenkaag", "hillegom", "kaag", "lisse", "lisserbroek", "noordwijkerhout", "nieuw vennep", "voorhout", "de zilk", "beinsdorp", "sassenheim" };
        private static string[] _0255 = { "0255", "velsen-zuid", "ijmuiden", "driehuis" };
        private static string[] _026 = { "026", "angeren", "arnhem", "heteren", "oosterbeek", "de steeg", "velp", "wolfheze", "westervoort", "deelen", "doorwerth", "driel", "huissen", "rozendaal", "rheden" };
        private static string[] _0294 = { "0294", "abcoude", "baambrugge", "muiderberg", "nederhorst den berg", "nigtevecht", "nieuwersluis", "nieuwer ter aa", "vreeland", "weesp", "loenen aan de vecht", "loenersloot", "muiden" };
        private static string[] _0297 = { "0297", "amstelhoek", "aalsmeer", "aalsmeerderbrug", "de hoef", "kudelstaart", "de kwakel", "mijdrecht", "rijsenhout", "uithoorn", "vinkeveen", "vrouwenakker", "wilnis", "waverveen", "rozenburg" };
        private static string[] _0299 = { "0299", "beets", "driehuizen", "graft", "grootschermer", "hobrede", "katwoude", "kwadijk", "middelie", "monnickendam", "noordeinde", "noordbeemster", "oosthuizen", "purmerland", "purmer", "de rijp", "volendam", "westbeemster", "warder", "wijdewormer", "zuidoostbeemster", "edam", "middenbeemster", "marken", "purmerend", "schardam" };
        private static string[] _030 = { "030", "bilthoven", "de bilt", "bosch en duin", "huis ter heide ut", "lopikerkapel", "de meern", "nieuwegein", "odijk", "oud zuilen", "utrecht", "vleuten", "ijsselstein ut", "zeist", "bunnik", "den dolder", "'t goy", "houten", "haarzuilens", "schalkwijk", "tull en 't waal" };
        private static string[] _0313 = { "0313", "angerlo", "doesburg", "drempt", "dieren", "ellecom", "giesbeek", "hall", "laag soeren", "lathum", "spankeren", "eerbeek" };
        private static string[] _0314 = { "0314", "azewijn", "doetinchem", "halle", "hoog keppel", "'s-heerenberg", "lengel", "laag keppel", "vethuizen", "wehl", "wijnbergen", "zeddam", "zelhem", "braamt", "hummelo", "kilder", "stokkum" };
        private static string[] _0315 = { "0315", "breedenbroek", "gendringen", "gaanderen", "heelweg", "netterden", "terborg", "ulft", "voorst", "varsselder veldhunten", "varsseveld", "westendorp", "dinxperlo", "etten", "de heurne", "megchelen", "sinderen", "sinderen", "silvolde" };
        private static string[] _0316 = { "0316", "aerdt", "babberich", "beek", "duiven", "lobith", "loo", "tolkamer", "zevenaar", "didam", "groessen", "herwen", "loerbeek", "pannerden", "spijk" };
        private static string[] _0317 = { "0317", "heelsum", "wageningen", "rhenen", "renkum" };
        private static string[] _0318 = { "0318", "ede", "elst", "harskamp", "de klomp", "lunteren", "renswoude", "veenendaal", "wekerom", "bennekom", "ederveen", "otterlo" };
        private static string[] _0320 = { "0320", "lelystad" };
        private static string[] _0321 = { "0321", "biddinghuizen", "swifterbant", "dronten" };
        private static string[] _033 = { "033", "amersfoort", "bunschoten spakenburg", "eemdijk", "hoogland", "hooglanderveen", "leusden", "nijkerk", "nijkerkerveen", "stoutenburg", "stoutenburg noord", "woudenberg", "hoevelaken", "scherpenzeel" };
        private static string[] _0341 = { "0341", "ermelo", "harderwijk", "hulshorst", "hierden", "nunspeet", "putten" };
        private static string[] _0342 = { "0342", "achterveld", "barneveld", "de glind", "kootwijkerbroek", "terschuur", "voorthuizen", "zwartebroek", "stroe" };
        private static string[] _0343 = { "0343", "amerongen", "austerlitz", "driebergen-rijsenburg", "doorn", "langbroek", "maarn", "wijk bij duurstede", "werkhoven", "cothen", "leersum", "maarsbergen", "overberg" };
        private static string[] _0344 = { "0344", "erichem", "eck en wiel", "ingen", "kerk avezaath tiel", "kerk avezaath", "kapel avezaath", "lienden", "ochten", "ommeren", "varik", "wadenoijen", "ijzendoorn", "zennewijnen", "zoelen", "buren", "echteld", "heesselt", "kapel avezaath buren", "maurik", "ophemert", "tiel" };
        private static string[] _0345 = { "0345", "acquoy", "asperen", "asch", "beusichem", "beesd", "buurmalsen", "deil", "enspijk", "est", "geldermalsen", "hei en boeicop", "heukelum", "leerdam", "oosterwijk", "rijswijk", "ravenswaaij", "schoonrewoerd", "tricht", "zijderveld", "zoelmond", "culemborg", "gellicum", "leerbroek", "meteren", "rhenoy", "rumpt" };
        private static string[] _0346 = { "0346", "breukelen", "groenekan", "maarssen", "maartensdijk", "soesterberg", "tienhoven", "westbroek", "kockengen" };
        private static string[] _0347 = { "0347", "everdingen", "hagestein", "ossenwaard", "vianen", "lexmond" };
        private static string[] _0348 = { "0348", "harmelen", "jaarsveld", "kamerik", "linschoten", "nieuwerbrug", "oudewater", "papekop", "snelrewaard", "waarder", "woerden", "zegveld", "benschop", "driebruggen", "lopik", "montfoort" };
        private static string[] _035 = { "035", "ankeveen", "blaricum", "breukeleveen", "bussum", "hollandsche rading", "hilversum", "huizen", "kortenhoef", "laren", "lage vuursche", "loosdrecht", "naarden", "soest", "baarn", "eemnes", "'s-graveland" };
        private static string[] _036 = { "036", "almere", "zeewolde" };
        private static string[] _038 = { "038", "genemuiden", "'s-heerenbroek", "hasselt", "hattemerbroek", "kampen", "kamperveen", "wilsum", "wapenveld", "wezep", "ijsselmuiden", "zwolle", "zalk", "zwartsluis", "belt schutsloot", "grafhorst", "hattem", "mastenbroek" };
        private static string[] _040 = { "040", "geldrop", "heeze", "leende", "nuenen", "sterksel", "veldhoven", "valkenswaard", "waalre", "westerhoven", "wintelre", "eindhoven", "knegsel", "riethoven" };
        private static string[] _0411 = { "0411", "cromvoirt", "haaren", "liempde", "boxtel", "esch", "helvoirt" };
        private static string[] _0412 = { "0412", "berghem", "heesch", "haren", "lithoijen", "maren kessel", "macharen", "megen", "nistelrode", "oss", "oijen", "teeffelen", "lith" };
        private static string[] _0413 = { "0413", "heeswijk dinther", "loosbroek", "odiliapeel", "sint oedenrode", "uden", "veghel", "volkel", "vorstenbosch", "erp" };
        private static string[] _0416 = { "0416", "babylonienbroek", "drunen", "drongelen", "elshout", "genderen", "heusden", "sprang-capelle", "veen", "waspik", "waalwijk", "wijk en aalburg", "dussen", "eethen", "kaatsheuvel", "loon op zand", "meeuwen" };
        private static string[] _0418 = { "0418", "aalst", "alem", "bruchem", "bern", "brakel", "delwijnen", "haaften", "herwijnen", "hellouw", "kerkwijk", "nederhemert", "neerijnen", "nieuwaal", "opijnen", "poederoijen", "rossum", "tuil", "velddriel", "waardenburg", "zaltbommel", "zuilichem", "gameren", "hurwenen", "hoenzadriel", "kerkdriel" };
        private static string[] _043 = { "043", "banholt", "bunde", "bemelen", "berg en terblijt", "beutenaken", "cadier en keer", "eckelrade", "elkenrade", "eys", "gulpen", "gronsveld", "sint geertruid", "heijenrath", "ingber", "lemiers", "mechelen", "mheer", "maastricht", "ransdaal", "reijmerstok", "scheulder", "schin op geul", "ulestraten", "vaals", "valkenburg", "vijlen", "walem", "wittem", "wijlre", "epen", "eijsden", "geulle", "maastricht-airport", "meerssen", "margraten", "moorveld", "noorbeek", "slenaken" };
        private static string[] _045 = { "045", "baneheide", "brunssum", "eygelshoven", "hoensbroek", "heerlen", "hulsberg", "klimmen", "kerkrade", "landgraaf", "nuth", "schinveld", "schimmert", "simpelveld", "voerendaal", "wijnandsrade", "bocholtz" };
        private static string[] _046 = { "046", "amstenrade", "beek", "bingelrade", "buchten", "doenrade", "einighausen", "geleen", "grevenbicht", "guttecoven", "holtum", "limbricht", "munstergeleen", "merkelbeek", "nieuwstadt", "obbicht", "oirsbeek", "roosteren", "spaubeek", "sittard", "stein", "urmond", "windraak", "born", "elsloo", "jabeek", "papenhoven", "puth", "schinnen", "susteren", "sweikhuizen" };
        private static string[] _0475 = { "0475", "baexem", "beegden", "buggenum", "echt", "grathem", "heibloem", "heel", "herkenbosch", "herten", "heythuysen", "haelen", "horn", "hunsel", "ittervoort", "sint joost", "koningsbosch", "linne", "maasbracht", "montfort", "neer", "neeritter", "nunhem", "sint odilienberg", "ohe en laak", "swalmen", "stevensweert", "thorn", "vlodrop", "wessem", "melick", "maria hoop", "posterholt", "roggel", "roermond" };
        private static string[] _0478 = { "0478", "blitterswijck", "geijsteren", "heide", "leunen", "maashees", "oirlo", "oostrum", "tienray", "venray", "veulen", "vierlingsbeek", "vredepeel", "wanssum", "well", "wellerlooi", "ysselsteyn", "castenray", "groeningen", "holthees", "meerlo", "merselo", "overloon", "smakt", "swolgen" };
        private static string[] _0481 = { "0481", "bemmel", "haalderen", "homoet", "oosterhout", "slijk ewijk", "doornenburg", "elst", "gendt", "kekerdom", "millingen aan de rijn", "ressen", "ressen" };
        private static string[] _0485 = { "0485", "afferden", "sint agatha", "bergen", "boxmeer", "beugen", "cuijk", "gennep", "sint hubert", "haps", "katwijk", "landhorst", "milsbeek", "mill", "oeffelt", "oploo", "ottersum", "rykevoort-de walsert", "sint anthonis", "sambeek", "stevensbeek", "vianen", "vortum mullem", "wilbertoord", "wanroij", "westerbeek", "beers", "heijen", "ledeacker", "linden", "rijkevoort", "siebengewald" };
        private static string[] _0486 = { "0486", "gassel", "grave", "herpen", "niftrik", "reek", "schaijk", "velp", "zeeland", "escharen", "langenboom", "ravenstein" };
        private static string[] _0487 = { "0487", "afferden", "alphen", "altforst", "appeltern", "batenburg", "bergharen", "beneden leeuwen", "dreumel", "hernen", "horssen", "heerewaarden", "maasbommel", "puiflijk", "winssen", "wamel", "boven leeuwen", "deest", "druten", "ewijk" };
        private static string[] _0488 = { "0488", "andelst", "herveld", "hemmen", "opheusden", "randwijk", "valburg", "zetten", "dodewaard", "kesteren" };
        private static string[] _0492 = { "0492", "aarle rixtel", "bakel", "beek en donk", "boekel", "elsendorp", "gemert", "handel", "helmond", "lierop", "milheeze", "mierlo", "de mortel", "venhorst" };
        private static string[] _0493 = { "0493", "asten", "deurne", "griendtsveen", "helenaveen", "liessel", "ommel", "de rips", "vlierden", "heusden", "someren" };
        private static string[] _0495 = { "0495", "budel dorplein", "budel", "budel-schoot", "haler", "kelpen-oler", "nederweert eind", "nederweert", "weert", "ell", "gastel", "leveroy", "maarheeze", "ospel", "soerendonk", "stramproy" };
        private static string[] _0497 = { "0497", "bergeijk", "bladel", "casteren", "duizel", "hoogeloon", "hapert", "netersel", "reusel", "steensel", "vessem", "eersel", "luyksgestel" };
        private static string[] _0499 = { "0499", "best", "oirschot", "breugel", "lieshout", "mariahout", "son" };
        private static string[] _050 = { "050", "adorp", "aduard", "sint annen", "alteveer", "bedum", "bunne", "garmerwolde", "de groeve", "den ham", "harkstede", "den horn", "haren", "leutingewolde", "lieveren", "lellens", "luddeweer", "midlaren", "matsloot", "noordwolde", "noordlaren", "nieuw roden", "onderdendam", "onnen", "oostwold", "paterswolde", "de punt", "roderesch", "schipborg", "sauwerd", "ten boer", "ten post", "waterhuizen", "winde", "winneweer", "westerbroek", "woltersum", "wetsinge", "yde", "zuidlaren", "zuidwolde", "eelde", "eelderwolde", "foxwolde", "glimmen", "groningen", "peize", "roderwolde", "roden", "scharmer", "thesinge" };
        private static string[] _0511 = { "0511", "augsbuurt", "burgum", "broeksterwoude", "buitenpost", "driesum", "engwierum", "garyp", "hurdegaryp", "kollum", "kollumerzwaag", "oudwoude", "ryptsjerk", "suwald", "triemen", "twijzelerheide", "twijzel", "veenklooster", "de valom", "veenwouden", "westergeest", "wouterswoude", "zwagerbosch", "zwaagwesteinde", "damwoude", "earnewald", "kollumerpomp", "noardburgum", "rinsumageest", "sumar", "tytsjerk" };
        private static string[] _0512 = { "0512", "augustinusga", "drachtstercompagnie", "drachten", "jistrum", "frieschepalen", "harkema", "houtigehage", "kootstertille", "kortehemmen", "nijega", "olterterp", "eastermar", "siegerswoude", "surhuizum", "de tike", "ureterp", "de veenhoop", "de wilgen", "boelenslaan", "boornbergum", "beetsterzwaag", "drogeham", "gerkesklooster", "nij beets", "opeinde", "oudega", "rottevalle", "stroobos", "surhuisterveen", "smalle ee" };
        private static string[] _0513 = { "0513", "broek", "doniaga", "dijken", "gersloot", "gorredijk", "haskerdijken", "haskerhorne", "idskenhuizen", "joure", "langezwaag", "lippenhuizen", "luinjeberd", "luxwoude", "mildam", "sint nicolaasga", "nijehaske", "nieuwehorne", "nieuwebrug", "nieuweschoot", "oldeouwer", "oudeschoot", "oudehaske", "ouwsterhaule", "oudehorne", "nieuwehorne", "rotstergaast", "rottum fr", "sintjohannesga", "snikzwaag", "terband", "teroele", "tjalleberd", "terwispel", "tijnje", "vegelinsoord", "bontebok", "boornzwaag", "heerenveen", "jonkerslan", "katlijk", "de knipe", "langweer", "legemeer", "oranjewoud", "ouwster nijega", "rohel", "rotsterhaule", "scharsterbrug" };
        private static string[] _0514 = { "0514", "balk", "bakhuizen", "echtenerbrug", "harich", "hindeloopen", "hemelum", "it heidenskip", "koudum", "lemmer", "molkwerum", "nijemirdum", "oudega gaast sleat", "oudemirdum", "oosterzee", "ruigahuizen", "smallebrugge", "sloten", "sondel", "tjerkgaast", "warns", "woudsend", "wijckel", "ypecolsga", "bantega", "delfstrahuizen", "echten", "eesterga", "elahuizen", "follega", "indijk", "koufurderrige", "kolderwolde", "mirns", "rijs", "stavoren" };
        private static string[] _0515 = { "0515", "abbega", "allingawier", "blauwhuis", "bolsward", "boazum", "cornwerd", "dedgum", "folsgare", "ferwoude", "gauw", "greonterp", "hartwerd", "hinnaard", "heeg", "hichtum", "hidaard", "hommerts", "hieslum", "idzega", "loenga", "nijhuizum", "nijland", "oudega", "offingawier", "oosthem", "oppenhuizen", "piaam", "sandfirden", "sibrandabuorren", "tjerkwerd", "tersoal", "uitwellingerga", "workum", "wommels", "wolsum", "westhem", "ysbrechtum", "ijlst", "burgwerd", "dearsum", "iens", "exmorra", "gaastmeer", "goenga", "gaast", "idsegahuizum", "itens", "jutrijp", "kubaard", "lytsewierrum", "makkum", "easterein", "parrega", "rien", "reahus", "scharnegoutum", "sneek", "tjalhuizum", "tirns" };
        private static string[] _0516 = { "0516", "appelscha", "bakkeveen", "donkerbroek", "een west", "haule", "haulerwijk", "hemrik", "jubbega", "langedijke", "nijeberkoop", "oldeberkoop", "ravenswoud", "waskemeer", "wijnjewoude", "fochteloo", "hoornsterzwaag", "makkinga", "oosterwolde" };
        private static string[] _0517 = { "0517", "achlum", "arum", "baard", "baaium", "boer", "herbaijum", "hitzum", "harlingen", "kimswerd", "kornwerderzand", "lollum", "easterlittens", "pietersbierum", "ried", "schalsum", "schettens", "schraard", "tzum", "waaksens", "winsum", "witmarsum", "wijnaldum", "wons", "wjelsryp", "zurich", "zweins", "breezanddijk", "dongjum", "dronrijp", "franeker", "huns", "longerhouw", "leons", "midlum", "peins", "pingjum", "schingen", "sexbierum", "spannum" };
        private static string[] _0518 = { "0518", "sint annaparochie", "ferwert", "hallum", "hegebeintum", "menaldum", "minnertsga", "oude bildtzijl", "oosterbierum", "oude leije", "tzummarum", "vrouwenparochie", "westhoek", "wier", "berlikum", "firdgum", "hijum", "sint jacobiparochie", "klooster lidlum", "marrum", "slappeterp" };
        private static string[] _0519 = { "0519", "aalzum", "ameland", "anjum", "ballum", "burdaard", "bornwird", "buren", "dokkum", "ee", "hantumeruitburen", "hiaure", "holwerd", "hantum", "hollum", "hantumhuizen", "jannum", "lauwersoog", "lioessens", "moddergat", "morra", "nes", "nes", "niawier", "oosternijkerk", "oostrum", "paesens", "raard", "schiermonnikoog", "wanswert", "waaxens", "wetzens", "wierum", "blije", "brantgum", "foudgum", "ginnum", "jislum", "jouswier", "lichtaard", "metslawier", "reitsum", "sijbrandahuis", "ternaard" };
        private static string[] _0521 = { "0521", "baars", "basse", "de bult", "diever", "dieverbrug", "dwingeloo", "frederiksoord", "giethoorn", "geeuwenbrug", "havelte", "havelterberg", "nijensleek", "onna", "de pol", "scheerwolde", "steenwijkerwold", "tuk", "uffelte", "vledder", "vledderveen", "wapserveen", "wateren", "wilhelminaoord", "witte paarden", "willemsoord", "wapse", "wetering", "wittelte", "zuidveen", "zorgvlied", "darp", "doldersum", "eesveen", "kallenkote", "marijenkampen", "oude willem", "steenwijk" };
        private static string[] _0522 = { "0522", "ansen", "broekhuizen", "de schiphorst", "koekange", "meppel", "nijeveen", "ruinerwold", "rogat", "rouveen", "wanneperveen", "ijhorst", "de wijk", "ruinen", "staphorst" };
        private static string[] _0523 = { "0523", "balkbrug", "beerzerveld", "beerze", "bruchterveld", "collendoorn", "drogteropslagen", "hardenberg", "hoogenweg", "heemserveen", "kloosterhaar", "marienberg", "radewijk", "rheeze", "rheezerveen", "sibculo", "venebrugge", "vinkenbuurt", "witharen", "brucht", "bergentheim", "dedemsvaart", "diffelen", "lutten", "slagharen", "schuinesloot" };
        private static string[] _0524 = { "0524", "ane", "anerveen", "anevelde", "coevorden", "dalerpeel", "geesbrug", "holthone", "holtheme", "nieuw schoonebeek", "oosterhesselen", "schoonebeek", "stieltjeskanaal", "den velde", "weiteveen", "wachtum", "zwinderen", "dalen", "dalerveen", "gramsbergen", "gees", "de krim", "loozen" };
        private static string[] _0525 = { "0525", "doornspijk", "'t harde", "noordeinde", "oldebroek", "'t loo oldebroek", "elburg", "oosterwolde" };
        private static string[] _0527 = { "0527", "blankenham", "bant", "ens", "emmeloord", "espel", "sint jansklooster", "kraggenburg", "kuinre", "luttelgeest", "nederland", "nagele", "urk", "vollenhove", "baarlo", "blokzijl", "creil", "marknesse", "rutten", "slijkenburg", "tollebeek" };
        private static string[] _0528 = { "0528", "alteveer", "alteveer", "elim", "eursinge", "fluitenberg", "hoogeveen", "hollandscheveld", "linde", "nieuw balinge", "noordscheschut", "nieuweroord", "nieuwlande coevorden", "nieuwlande", "pesse", "stuifzand", "veeningen", "zuidwolde", "echten", "kerkenveld", "tiendeveen" };
        private static string[] _0529 = { "0529", "arrien", "dalfsen", "giethmen", "laag zuthem", "nieuwleusen", "ommen", "punthorst", "stegeren", "vilsteren" };
        private static string[] _053 = { "053", "glane", "haaksbergen", "overdinkel", "enschede", "losser" };
        private static string[] _0541 = { "0541", "agelo", "beuningen", "denekamp", "haarle", "hezingen", "manderveen", "nutter", "oldenzaal", "ootmarsum", "oud ootmarsum", "reutum", "vasse", "weerselo", "lattrop breklenkamp", "de lutte", "mander", "rossum", "tilligte" };
        private static string[] _0543 = { "0543", "aalten", "bredevoort", "winterswijk", "winterswijk corle", "winterswijk henxel", "heurne", "winterswijk huppel", "winterswijk kotten", "winterswijk meddo", "winterswijk woold", "winterswijk", "winterswijk brinkheurne", "winterswijk miste", "winterswijk ratum" };
        private static string[] _0544 = { "0544", "beltrum", "groenlo", "harreveld", "vragender", "zieuwent", "lichtenvoorde", "lievelde", "marienvelde" };
        private static string[] _0545 = { "0545", "borculo", "eibergen", "gelselaar", "haarlo", "neede", "rekken", "geesteren", "rietmolen" };
        private static string[] _0546 = { "0546", "aadorp", "albergen", "almelo", "bruinehaar", "daarle", "daarlerveen", "fleringen", "geesteren", "den ham", "harbrinkhoek", "hoge hexel", "langeveen", "mariaparochie", "tubbergen", "vroomshoop", "vriezenveen", "wierden", "westerhaar-vriezenv wijk" };
        private static string[] _0547 = { "0547", "bentelo", "diepenheim", "goor", "hengevelde", "markelo", "enter" };
        private static string[] _0548 = { "0548", "hellendoorn", "haarle", "holten", "notter", "nijverdal", "rijssen", "zuna" };
        private static string[] _055 = { "055", "apeldoorn", "beekbergen", "beemte broekland", "hoenderloo", "teuge", "ugchelen", "wenum wiesel", "hoog soeren", "klarenbeek", "loenen", "lieren" };
        private static string[] _0561 = { "0561", "blesdijke", "de blesse", "boschoord", "de hoeve", "kalenberg", "munnekeburen", "nijeholtpade", "nijeholtwolde", "nijelamer", "nijetrijne", "noordwolde", "oldeholtpade", "oldelamer", "oldemarkt", "oldetrijne", "oldeholtwolde", "ossenzijl", "scherpenzeel", "ter idzard", "vinkega", "wolvega", "ijsselham", "zandhuizen", "boijl", "elsloo", "langelille", "oosterstreek", "paasloo", "peperga", "steggerda", "sonnega", "spanga" };
        private static string[] _0562 = { "0562", "baaiduinen", "hee", "hoorn", "kaart", " midsland", "terschelling", "vlieland", "west", "formerum", "kinnum", "landerum", "lies", "oosterend", "seeryp" };
        private static string[] _0566 = { "0566", "akkrum", "akmarijp", "friens", "goengahuizen", "grou", "jirnsum", "nes", "aldeboarn", "poppenwier", "reduzum", "terkaple", "goingarijp", "idaerd", "raerd", "terherne" };
        private static string[] _0570 = { "0570", "bathmen", "broekland", "colmschate", "lettele", "okkenbroek", "olst", "schalkhaar", "wijhe", "welsum", "wesepe", "diepenveen", "deventer", "steenenkamer" };
        private static string[] _0571 = { "0571", "nijbroek", "terwolde", "twello", "wilp" };
        private static string[] _0572 = { "0572", "dalmsholte", "heeten", "heino", "luttenberg", "marienheem", "nieuw heeten", "raalte", "lierderholthuis", "lemele", "lemelerveld" };
        private static string[] _0573 = { "0573", "barchem", "harfsen", "kring van dorth", "lochem", "ruurlo", "laren" };
        private static string[] _0575 = { "0575", "almen", "baak", "bronkhorst", "eefde", "empe", "epse", "hengelo", "keijenborg", "leuvenheim", "olburgen", "rha", "tonden", "vorden", "vierakker", "voorst", "wichmond", "warnsveld", "zutphen", "brummen", "gorssel", "joppe", "steenderen", "toldijk" };
        private static string[] _0577 = { "0577", "kootwijk", "uddel", "vierhouten", "elspeet", "garderen" };
        private static string[] _0578 = { "0578", "emst", "epe", "heerde", "oene", "vorchten", "veessen", "vaassen", "marle" };
        private static string[] _058 = { "058", "eagum", "beetgumermolen", "beetgum", "bears", "britsum", "britswert", "cornjum", "deinum", "finkum", "goutum", "hempens", "hilaard", "jelsum", "jellum", "lekkum", "leeuwarden", "marssum", "munein", "aldtsjerk", "oentsjerk", "easterwierrum", "roodkerk", "swichum", "warstiens", "wirdum", "weidum", "wiuwert", "wergea", "warten", "wyns", "wijtgaard", "blessum", "boksum", "engelum", "gytsjerk", "jorwert", "mantgum", "miedum", "snakkerburen", "stiens", "teerns" };
        private static string[] _0591 = { "0591", "aalden", "barger compascuum", "benneveld", "emmer compascuum", "emmen", "erm", "exloo", "'t haantje", "holsloot", "klazienaveen", "klijndijk", "meppen", "nieuw amsterdam", "nieuw dordrecht", "noord sleen", "nieuw weerdinge", "odoorn", "odoornerveen", "schoonoord", "veenoord", "valthe", "wezup", "wezuperbrug", "zweeloo", "zwartemeer", "zandpol", "diphoorn", "erica", "de kiel", "roswinkel", "sleen" };
        private static string[] _0592 = { "0592", "amen", "anderen", "anloo", "annen", "assen", "balloo", "balloerveld", "bovensmilde", "deurze", "donderen", "eldersloo", "een", "eext", "eleveld", "grolloo", "gasteren", "gieten", "huis ter heide", "hoogersmilde", "langelo", "nooitgedacht", "norg", "nijlande", "oudemolen", "oranje", "peest", "papenvoort", "rhee", "rolde", "steenbergen", "schoonloo", "tynaarlo", "ter aard", "ubbena", "veenhuizen", "vredenheim", "vries", "westervelde", "zeegse", "zeijerveld", "zeijerveen", "zuidvelde", "zeijen", "ekehaar", "geelbroek", "loon", "marwijksoord", "smilde", "taarlo" };
        private static string[] _0593 = { "0593", "beilen", "balinge", "elp", "eursinge", "hooghalen", "hijken", "mantinge", "orvelte", "westerbork", "witteveen", "wijster", "zuidveld", "zwiggelte", "bruntinge", "drijber", "garminge", "spier" };
        private static string[] _0594 = { "0594", "boerakker", "briltil", "boerakker", "burum", "feerwerd", "grijpskerk", "grootegast", "garnwerd", "jonkersvaart", "kornhorn", "lettelbert", "marum", "midwolde", "niebert", "noordhorn", "nietap", "niezijl", "niehove", "niekerk grootegast", "noordwijk", "nuis", "oldehove", "oldekerk", "opende", "sebaldeburen", "visvliet", "warfstermolen", "de wilp", "zuidhorn", "zevenhuizen", "doezum", "enumatil", "ezinge", "kommerzijl", "leek", "lutjegast", "lucaswolde", "lauwerzijl", "munnekezijl", "pieterzijl", "saaksum", "tolbert" };
        private static string[] _0595 = { "0595", "den andel", "baflo", "garsthuizen", "hornhuizen", "houwerzijl", "huizinge", "kloosterburen", "kantens", "leens", "niekerk de marne", "oosternieland", "pieterburen", "roodeschool", "rottum", "schouwerzijl", "startenhuizen lopp", "stitswerd", "tinallinge", "toornwerd", "uithuizermeeden", "uithuizen", "ulrum", "usquert", "vierhuizen", "warffum", "wehe den hoorn", "warfhuizen", "winsum", "westernieland", "westerwijtwerd", "zandeweer", "zoutkamp", "zuurdijk", "eppenhuizen", "eenrum", "middelstum", "mensingeweer", "oldenzijl", "rasquert", "startenhuizen", "saaxumhuizen" };
        private static string[] _0596 = { "0596", "appingedam", "bierum", "borgsweer", "eemshaven", "holwierde", "krewerd", "losdorp", "loppersum", "leermens", "nieuwolda", "oudeschip", "spijk", "stedum", "termunten", "wagenborgen", "wirdum", "woldendorp", "westeremden", "'t zandt", "zijldijk", "zeerijp", "delfzijl", "eenum", "farmsum", "godlinze", "garrelsweer", "meedhuizen", "overschild", "oosterwijtwerd", "termunterzijl", "tjuchem" };
        private static string[] _0597 = { "0597", "blijham", "finsterwolde", "heiligerlee", "midwolda", "nieuw beerta", "nieuwe pekela", "nieuweschans", "oude pekela", "oudeschans", "oostwold scheemda", "oudezijl", "scheemda", "veelerveen", "vriescheloo", "wedde", "westerlee", "winschoten", "bellingwolde", "beerta", "drieborg" };
        private static string[] _0598 = { "0598", "annerveensche kanaal", "borgercompagnie", "eexterveensche kanaal", "eexterveen", "foxhol", "hoogezand", "hellum", "kolham", "kiel windeweer", "lageland", "muntendam", "nieuwediep", "noordbroek", "nieuw scheemda", "oud annerveen", "schildwolde", "siddeburen", "slochteren", "spijkerboor", "sappemeer", "tripscompagnie", "veendam", "'t waar", "woudbloem", "wildervank", "zuidbroek", "zuidlaarderveen", "eexterzandvoort", "froombosch", "kropswolde", "meeden", "nieuw annerveen", "steendam" };
        private static string[] _0599 = { "0599", "ter apel", "alteveer", "borger", "bronnegerveen", "buinen", "drouwenerveen", "ees", "eesergroen", "tweede exloermond", "exloerveen", "gasselternijveen", "gasselternijveenschemond", "gieterveen", "musselkanaal", "mussel", "onstwedde", "stadskanaal", "ter apelkanaal", "valthermond", "vledderveen", "vlagtwedde", "tweede valthermond", "westdorp", "zandberg", "bourtange", "bronneger", "buinerveen", "drouwen", "drouwenermond", "ellertshaar", "eeserveen", "eerste exloermond", "gasselte", "nieuw buinen", "sellingen" };
        private static string[] _070 = { "070", "s-gravenhage", "voorburg", "wassenaar", "leidschendam", "rijswijk" };
        private static string[] _071 = { "071", "oud ade", "hazerswoude rijndijk", "hoogmade", "leiderdorp", "leiden", "noordwijk", "nieuwe wetering", "oude wetering", "oegstgeest", "rijnsburg", "rijpwetering", "valkenburg", "voorschoten", "warmond", "weteringbrug", "zoeterwoude", "katwijk", "koudekerk aan den rijn", "roelofarendsveen" };
        private static string[] _072 = { "072", "alkmaar", "bergen", "bergen aan zee", "egmond-binnen", "groet", "heerhugowaard", "heiloo", "koedijk", "oudorp", "sint pancras", "schermerhorn", "stompetoren", "ursem", "ursem", "zuidschermer", "egmond aan zee", "egmond aan den hoef", "limmen", "oterleek", "schoorl" };
        private static string[] _073 = { "073", "ammerzoden", "berlicum", "den dungen", "geffen", "gemonde", "hedel", "haarsteeg", "'s-hertogenbosch", "sint michielsgestel", "nieuwkuijk", "nuland", "rosmalen", "schijndel", "vlijmen", "vinkel", "vught", "well" };
        private static string[] _074 = { "074", "ambt delden", "borne", "delden", "hertme", "hengelo", "saasveld", "zenderen", "bornerbroek", "deurningen" };
        private static string[] _075 = { "075", "assendelft", "jisp", "krommenie", "koog aan de zaan", "markenbinnen", "oost graftdijk", "oostknollendam", "oostzaan", "starnmeer", "de woude", "west graftdijk", "westknollendam", "wormerveer", "wormer", "westzaan", "zaandam", "zaandijk", "zaanstad", "spijkerboor" };
        private static string[] _076 = { "076", "achtmaal", "breda", "etten-leur", "galder", "strijbeek", "teteringen", "ulvenhout", "ulvenhout ac", "wagenberg", "wernhout", "zundert", "prinsenbeek", "rijsbergen", "terheijden" };
        private static string[] _077 = { "077", "arcen", "america", "beesel", "belfeld", "broekhuizen", "baarlo", "beringe", "broekhuizenvorst", "hegelsom", "helden", "horst", "kessel", "koningslust", "maasbree", "meterik", "neerkant", "panningen", "steijl", "tegelen", "velden", "venlo", "egchel", "evertsoord", "grubbenvorst", "grashoek", "kronenberg", "lomm", "lottum", "meijel", "melderslo", "reuver", "sevenum" };
        private static string[] _078 = { "078", "alblasserdam", "dordrecht", "hendrik ido ambacht", "heerjansdam", "mookhoek", "papendrecht", "strijen", "zwijndrecht", "'s-gravendeel", "kinderdijk", "maasdam", "puttershoek", "strijensas" };
        private static string[] _079 = { "079", "benthuizen", "gelderswoude", "moerkapelle", "zoetermeer" };
        private static List<string[]> netnummers =new List<string[]> { _010, _0111, _0113, _0114, _0115, _0117, _0118, _013, _015, _0161, _0162, _0164, _0165, _0166, _0167, _0168, _0172, _0174, _0180, _0181, _0182, _0183, _0184, _0186, _0187, _020, _0222, _0223, _0224, _0226, _0227, _0228, _0229, _023, _024, _0251, _0252, _0255, _026, _0294, _0297, _0299, _030, _0313, _0314, _0315,_0316,_0317,_0318,_0320,_0321,_033,_0341,_0342,_0343,_0344,_0345,_0346,_0347,_0348,_035,_036,_038,_040,_0411,_0412,_0413,_0416,_0418,_043,_045,_046,_0475,_0478,_0481,_0485,_0486,_0487,_0488,_0492,_0493,_0495,_0497,_0499,_050,_0511,_0512,_0513,_0514,_0515,_0516,_0517,_0518,_0519,_0521,_0522,_0523,_0524,_0525,_0527,_0528,_0529,_053,_0541,_0543,_0544,_0545,_0546,_0547,_0548,_055,_0561,_0562,_0566,_0570,_0571,_0572,_0573,_0575,_0577,_0578,_058,_0591,_0592,_0593,_0594,_0595,_0596,_0597,_0598,_0599,_070,_071,_072,_073,_074,_075,_076,_077,_078,_079 };
        public static Stack<string> GetNetNR(string pltsnaam)
        {
            Stack<string> returnNrs = new Stack<string>();
            int i = 0;
            foreach (string[] pltsnamen in netnummers)
            { i++;
                if(IsNetNR(pltsnamen,pltsnaam))
                {
                    returnNrs.Push(pltsnamen[0]);
                }
            }
            return returnNrs;
        }
        private static bool IsNetNR(string[] netnr, string pltsnm)
        {
            bool retval = false;
            string plaats = pltsnm;
            if (plaats.Length > 0)
            {
                for (int i = 0; i < netnr.Length; i++)
                {
                    if ((plaats.IndexOf(netnr[i], StringComparison.OrdinalIgnoreCase) >= 0))
                    {
                        //
                        //Handle the discovery of suspicious Sql characters here
                        //
                        retval = true;

                    }
                }
               
            }
            return retval;
           
        }
    }
}
