<?xml version="1.0" encoding="utf-8"?><Database Name="zeebregtsdb" Class="linq2sqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SQL-SERVER;Initial Catalog=zeebregtsdb;Persist Security Info=True;User ID=daan" SettingsObjectName="zeebregtsCs.Properties.Settings" SettingsPropertyName="zeebregtsdbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bedrijf" Member="bedrijfs">
    <Type Name="bedrijf">
      <Column Name="bedrijf_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bedrijf_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="naam" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="zoeknaam" Type="System.String" DbType="NVarChar(52)" CanBeNull="true" />
      <Column Name="straat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="plaats" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="postSTRAAT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="postPOSTCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="postPLAATS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mobiel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bank" Type="System.String" DbType="NVarChar(175)" CanBeNull="true" />
      <Column Name="Grek" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kvk" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kvkUITGIFTE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="kvkSCAN" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="omzetbelastingnr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="loonbelastingnr" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bedrijfverenigingnr" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NIETactief" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SWIFT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="debiteurNRzeebregts" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="crediteurNRzeebregts" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kostenplaats" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="postVIApostbus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="adres_id_bezoek" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adres_id_post" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefoon_nr_settings" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telefoon_nr_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telefoon_nr_2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telefoon_nr_3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.persoon" Member="persoons">
    <Type Name="persoon">
      <Column Name="persoon_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="taak_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bedrijf_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="man" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="voorletters" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="voornaam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tussenvoegsel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="achternaam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zamobiel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zatelefoonvast" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zafax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zaemail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="geboortedatum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vastevrijedag1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vastevrijedag2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vastevrijedag3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NIETactief" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="adres_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefoon_nr_settings" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telefoon_nr_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telefoon_nr_2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telefoon_nr_3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.project" Member="projects">
    <Type Name="project">
      <Column Name="project_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="project_NR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hoofdproject_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="aannemer_projectnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="aannemer_contractnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="naam_project" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="opdrachtgeverZEEBREGTS_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="plaats" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="aannemer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="off_aanvraag" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="off_verstuurd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="off_def" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[0off_volg]" Member="_0off_volg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[0off_versie]" Member="_0off_versie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[0off_aanvraag]" Member="_0off_aanvraag" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[0off_verstuurd]" Member="_0off_verstuurd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nagebeld" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[0off_def]" Member="_0off_def" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[prov_vast_aan%]" Member="prov_vast_aan_" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[prov_vast_aan_meerwerk%]" Member="prov_vast_aan_meerwerk_" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="verekenmethode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="exel_master" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="administratieCHECK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="betalingstermijn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verpakkenPER_0_offerte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verpakkenper_vloer" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="verpaken_per_wand" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[index%]" Member="index_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="garantie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lijm" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stelpostwand" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="stelpostvloer" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="opslagprijs_koper" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="opslagmeters_koper" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="deadline_0off" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deadline_off" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="verpVIAbestelling" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start_check" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="start_uitvoer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="planning_start_week" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="planning_start_jaar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="planning_eind_week" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="planning_eind_jaar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bouw_snelheid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bouw_straat" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="bouw_postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bouw_tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bouw_fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="verkoopbrochure" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NAWgegevens" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="[0_tekeningen]" Member="_0_tekeningen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FACTORnietAW_Zeebregts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FACTORcorrectie_Offerte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[coordiatiekostenbouwbedrijf%]" Member="coordiatiekostenbouwbedrijf_" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="switchcontract" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contact_leverancier_luxetegels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contact_leverancier_hoekprofielen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contact_leverancier_standaardtegels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="memo_aanvraag" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="STABU_groep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[STABU_groep_ja/nee]" Member="STABU_groep_ja_nee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="nacalculatiecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="INafbouwCONTROL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="aantal_koopwoningen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="omschrijvingKoopwoningen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="factuur_aanhef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="factuur_adres" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="factuur_postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="factuur_plaats" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UITvia0offerte" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="[0off_aanv]" Member="_0off_aanv" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="[0off_annv_omschrijving]" Member="_0off_annv_omschrijving" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="inkoper_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="werkvoorbereider_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="projectleider_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uitvoerder_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kopersbegeleider_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contactpersoonTegelshowroom_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contactpersoonSANITAIRshowroom_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contactpersoonKEUKENshowroom_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="offerte_persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[0offerte_persoon_nr]" Member="_0offerte_persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="koperofferte_persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uitvoerderAfbouw_persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uitvoerderZeebregts_persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tegelzetter_persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[opzichter_persoon-nr]" Member="opzichter_persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bouwbedrijf_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kopersbegeleidingbedrijf_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="facturatieMEERWERKbedrijf_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="betalingbedrijf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tegelshowroom_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sanitairshowroom_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="keukenshowroom_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="projectontwikkelaar_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[showroom-PARTNER-NR]" Member="showroom_PARTNER_NR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[leverancier-HOEKPROFIELEN]" Member="leverancier_HOEKPROFIELEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[leverancier-STANDAARD]" Member="leverancier_STANDAARD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[opdrachtgever-bestelling-partner-nr]" Member="opdrachtgever_bestelling_partner_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verpakkingstoeslagUpgrade" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="projectNRadminZeebregts" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="adres_id_bouw" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adres_id_factuur" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="status_project" Member="status1" ThisKey="status" OtherKey="id" Type="status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.status" Member="status">
    <Type Name="status">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="omschrijving_nr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="omschrijving" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="volgorde" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="planning" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="status_project" Member="projects" ThisKey="id" OtherKey="status" Type="project" />
    </Type>
  </Table>
  <Function Name="dbo.Dubbel_inv_list_pers" Method="Dubbel_inv_list_pers">
    <Parameter Name="voornaam" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="voorletters" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="achternaam" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="bedrijf_nr" Type="System.Int32" DbType="Int" />
    <Parameter Name="man" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="Dubbel_inv_list_persResult">
      <Column Name="persoon_nr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="voornaam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="achternaam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zoeknaam" Type="System.String" DbType="NVarChar(52)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>