#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR2PDF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MandagenRegistratie")]
	public partial class dbLMandagenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGebruiker(Gebruiker instance);
    partial void UpdateGebruiker(Gebruiker instance);
    partial void DeleteGebruiker(Gebruiker instance);
    partial void InsertLoonkosten(Loonkosten instance);
    partial void UpdateLoonkosten(Loonkosten instance);
    partial void DeleteLoonkosten(Loonkosten instance);
    #endregion
		
		
		public dbLMandagenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLMandagenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLMandagenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLMandagenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Mandagen> Mandagens
		{
			get
			{
				return this.GetTable<Mandagen>();
			}
		}
		
		public System.Data.Linq.Table<Vakman> Vakmans
		{
			get
			{
				return this.GetTable<Vakman>();
			}
		}
		
		public System.Data.Linq.Table<Gebruiker> Gebruikers
		{
			get
			{
				return this.GetTable<Gebruiker>();
			}
		}
		
		public System.Data.Linq.Table<Loonkosten> Loonkostens
		{
			get
			{
				return this.GetTable<Loonkosten>();
			}
		}
		
		public System.Data.Linq.Table<vwVakmanRelaty> vwVakmanRelaties
		{
			get
			{
				return this.GetTable<vwVakmanRelaty>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mandagen")]
	public partial class Mandagen
	{
		
		private int _ProjectId;
		
		private int _VakmanId;
		
		private int _VakmanstatusId;
		
		private System.DateTime _Begintijd;
		
		private System.DateTime _Eindtijd;
		
		private bool _Status;
		
		private int _Uren;
		
		private int _Minuten;
		
		private int _UrenGewijzigd;
		
		private int _MinutenGewijzigd;
		
		private int _VakmansoortId;
		
		private int _ProjectleiderId;
		
		private bool _Geannulleerd;
		
		private bool _Gewijzigd;
		
		private bool _Bevestigd;
		
		private System.Nullable<System.DateTime> _Bevestigingsdatum;
		
		private bool _IsChauffeurHeen;
		
		private bool _IsChauffeurTerug;
		
		private string _KentekenHeen;
		
		private string _KentekenTerug;
		
		private bool _Definitief;
		
		private System.DateTime _Mutatiedatum;
		
		private int _MutatieDoorProjectleiderId;
		
		public Mandagen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectId", DbType="Int NOT NULL")]
		public int ProjectId
		{
			get
			{
				return this._ProjectId;
			}
			set
			{
				if ((this._ProjectId != value))
				{
					this._ProjectId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VakmanId", DbType="Int NOT NULL")]
		public int VakmanId
		{
			get
			{
				return this._VakmanId;
			}
			set
			{
				if ((this._VakmanId != value))
				{
					this._VakmanId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VakmanstatusId", DbType="Int NOT NULL")]
		public int VakmanstatusId
		{
			get
			{
				return this._VakmanstatusId;
			}
			set
			{
				if ((this._VakmanstatusId != value))
				{
					this._VakmanstatusId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Begintijd", DbType="DateTime NOT NULL")]
		public System.DateTime Begintijd
		{
			get
			{
				return this._Begintijd;
			}
			set
			{
				if ((this._Begintijd != value))
				{
					this._Begintijd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eindtijd", DbType="DateTime NOT NULL")]
		public System.DateTime Eindtijd
		{
			get
			{
				return this._Eindtijd;
			}
			set
			{
				if ((this._Eindtijd != value))
				{
					this._Eindtijd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uren", DbType="Int NOT NULL")]
		public int Uren
		{
			get
			{
				return this._Uren;
			}
			set
			{
				if ((this._Uren != value))
				{
					this._Uren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minuten", DbType="Int NOT NULL")]
		public int Minuten
		{
			get
			{
				return this._Minuten;
			}
			set
			{
				if ((this._Minuten != value))
				{
					this._Minuten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrenGewijzigd", DbType="Int NOT NULL")]
		public int UrenGewijzigd
		{
			get
			{
				return this._UrenGewijzigd;
			}
			set
			{
				if ((this._UrenGewijzigd != value))
				{
					this._UrenGewijzigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinutenGewijzigd", DbType="Int NOT NULL")]
		public int MinutenGewijzigd
		{
			get
			{
				return this._MinutenGewijzigd;
			}
			set
			{
				if ((this._MinutenGewijzigd != value))
				{
					this._MinutenGewijzigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VakmansoortId", DbType="Int NOT NULL")]
		public int VakmansoortId
		{
			get
			{
				return this._VakmansoortId;
			}
			set
			{
				if ((this._VakmansoortId != value))
				{
					this._VakmansoortId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectleiderId", DbType="Int NOT NULL")]
		public int ProjectleiderId
		{
			get
			{
				return this._ProjectleiderId;
			}
			set
			{
				if ((this._ProjectleiderId != value))
				{
					this._ProjectleiderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geannulleerd", DbType="Bit NOT NULL")]
		public bool Geannulleerd
		{
			get
			{
				return this._Geannulleerd;
			}
			set
			{
				if ((this._Geannulleerd != value))
				{
					this._Geannulleerd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gewijzigd", DbType="Bit NOT NULL")]
		public bool Gewijzigd
		{
			get
			{
				return this._Gewijzigd;
			}
			set
			{
				if ((this._Gewijzigd != value))
				{
					this._Gewijzigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bevestigd", DbType="Bit NOT NULL")]
		public bool Bevestigd
		{
			get
			{
				return this._Bevestigd;
			}
			set
			{
				if ((this._Bevestigd != value))
				{
					this._Bevestigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bevestigingsdatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> Bevestigingsdatum
		{
			get
			{
				return this._Bevestigingsdatum;
			}
			set
			{
				if ((this._Bevestigingsdatum != value))
				{
					this._Bevestigingsdatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurHeen", DbType="Bit NOT NULL")]
		public bool IsChauffeurHeen
		{
			get
			{
				return this._IsChauffeurHeen;
			}
			set
			{
				if ((this._IsChauffeurHeen != value))
				{
					this._IsChauffeurHeen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurTerug", DbType="Bit NOT NULL")]
		public bool IsChauffeurTerug
		{
			get
			{
				return this._IsChauffeurTerug;
			}
			set
			{
				if ((this._IsChauffeurTerug != value))
				{
					this._IsChauffeurTerug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KentekenHeen", DbType="NVarChar(50)")]
		public string KentekenHeen
		{
			get
			{
				return this._KentekenHeen;
			}
			set
			{
				if ((this._KentekenHeen != value))
				{
					this._KentekenHeen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KentekenTerug", DbType="NVarChar(50)")]
		public string KentekenTerug
		{
			get
			{
				return this._KentekenTerug;
			}
			set
			{
				if ((this._KentekenTerug != value))
				{
					this._KentekenTerug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Definitief", DbType="Bit NOT NULL")]
		public bool Definitief
		{
			get
			{
				return this._Definitief;
			}
			set
			{
				if ((this._Definitief != value))
				{
					this._Definitief = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mutatiedatum", DbType="DateTime NOT NULL")]
		public System.DateTime Mutatiedatum
		{
			get
			{
				return this._Mutatiedatum;
			}
			set
			{
				if ((this._Mutatiedatum != value))
				{
					this._Mutatiedatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MutatieDoorProjectleiderId", DbType="Int NOT NULL")]
		public int MutatieDoorProjectleiderId
		{
			get
			{
				return this._MutatieDoorProjectleiderId;
			}
			set
			{
				if ((this._MutatieDoorProjectleiderId != value))
				{
					this._MutatieDoorProjectleiderId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vakman")]
	public partial class Vakman
	{
		
		private int _VakmanId;
		
		private int _ContactIdOrigineel;
		
		private System.Nullable<int> _BedrijfId;
		
		private bool _Actief;
		
		private bool _Intern;
		
		private System.Nullable<bool> _ZZP;
		
		private string _Bsn;
		
		private System.Nullable<decimal> _Loonkosten;
		
		private System.Data.Linq.Binary _Var;
		
		private System.Data.Linq.Binary _Kvk;
		
		private System.Nullable<int> _ProjectleiderId;
		
		private string _Adres;
		
		private string _Postcode;
		
		private string _Huisnummer;
		
		private string _Plaats;
		
		private string _Land;
		
		private string _Ophaaladres;
		
		private string _Ophaalpostcode;
		
		private string _Ophaalhuisnummer;
		
		private string _Ophaalplaats;
		
		private string _Ophaalland;
		
		private bool _IsChauffeur;
		
		private bool _IsChauffeurMa;
		
		private bool _IsChauffeurDi;
		
		private bool _IsChauffeurWo;
		
		private bool _IsChauffeurDo;
		
		private bool _IsChauffeurVr;
		
		private bool _IsChauffeurZa;
		
		private bool _IsChauffeurZo;
		
		private bool _IsBijrijder;
		
		private bool _IsBijrijderMa;
		
		private bool _IsBijrijderDi;
		
		private bool _IsBijrijderWo;
		
		private bool _IsBijrijderDo;
		
		private bool _IsBijrijderVr;
		
		private bool _IsBijrijderZa;
		
		private bool _IsBijrijderZo;
		
		private string _Kenteken;
		
		private System.Nullable<decimal> _Ma;
		
		private System.Nullable<decimal> _Di;
		
		private System.Nullable<decimal> _Wo;
		
		private System.Nullable<decimal> _Do;
		
		private System.Nullable<decimal> _Vr;
		
		private System.Nullable<decimal> _Za;
		
		private System.Nullable<decimal> _Zo;
		
		private System.Nullable<decimal> _Werkweek;
		
		private System.Nullable<int> _DefaultBeginuur;
		
		private System.Nullable<int> _DefaultBeginminuut;
		
		public Vakman()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VakmanId", DbType="Int NOT NULL")]
		public int VakmanId
		{
			get
			{
				return this._VakmanId;
			}
			set
			{
				if ((this._VakmanId != value))
				{
					this._VakmanId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactIdOrigineel", DbType="Int NOT NULL")]
		public int ContactIdOrigineel
		{
			get
			{
				return this._ContactIdOrigineel;
			}
			set
			{
				if ((this._ContactIdOrigineel != value))
				{
					this._ContactIdOrigineel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedrijfId", DbType="Int")]
		public System.Nullable<int> BedrijfId
		{
			get
			{
				return this._BedrijfId;
			}
			set
			{
				if ((this._BedrijfId != value))
				{
					this._BedrijfId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actief", DbType="Bit NOT NULL")]
		public bool Actief
		{
			get
			{
				return this._Actief;
			}
			set
			{
				if ((this._Actief != value))
				{
					this._Actief = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intern", DbType="Bit NOT NULL")]
		public bool Intern
		{
			get
			{
				return this._Intern;
			}
			set
			{
				if ((this._Intern != value))
				{
					this._Intern = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZZP", DbType="Bit")]
		public System.Nullable<bool> ZZP
		{
			get
			{
				return this._ZZP;
			}
			set
			{
				if ((this._ZZP != value))
				{
					this._ZZP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bsn", DbType="NVarChar(50)")]
		public string Bsn
		{
			get
			{
				return this._Bsn;
			}
			set
			{
				if ((this._Bsn != value))
				{
					this._Bsn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loonkosten", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Loonkosten
		{
			get
			{
				return this._Loonkosten;
			}
			set
			{
				if ((this._Loonkosten != value))
				{
					this._Loonkosten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Var]", Storage="_Var", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Var
		{
			get
			{
				return this._Var;
			}
			set
			{
				if ((this._Var != value))
				{
					this._Var = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kvk", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Kvk
		{
			get
			{
				return this._Kvk;
			}
			set
			{
				if ((this._Kvk != value))
				{
					this._Kvk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectleiderId", DbType="Int")]
		public System.Nullable<int> ProjectleiderId
		{
			get
			{
				return this._ProjectleiderId;
			}
			set
			{
				if ((this._ProjectleiderId != value))
				{
					this._ProjectleiderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huisnummer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Huisnummer
		{
			get
			{
				return this._Huisnummer;
			}
			set
			{
				if ((this._Huisnummer != value))
				{
					this._Huisnummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plaats", DbType="NVarChar(MAX)")]
		public string Plaats
		{
			get
			{
				return this._Plaats;
			}
			set
			{
				if ((this._Plaats != value))
				{
					this._Plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Land", DbType="NVarChar(MAX)")]
		public string Land
		{
			get
			{
				return this._Land;
			}
			set
			{
				if ((this._Land != value))
				{
					this._Land = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ophaaladres", DbType="NVarChar(MAX)")]
		public string Ophaaladres
		{
			get
			{
				return this._Ophaaladres;
			}
			set
			{
				if ((this._Ophaaladres != value))
				{
					this._Ophaaladres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ophaalpostcode", DbType="NVarChar(50)")]
		public string Ophaalpostcode
		{
			get
			{
				return this._Ophaalpostcode;
			}
			set
			{
				if ((this._Ophaalpostcode != value))
				{
					this._Ophaalpostcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ophaalhuisnummer", DbType="NVarChar(50)")]
		public string Ophaalhuisnummer
		{
			get
			{
				return this._Ophaalhuisnummer;
			}
			set
			{
				if ((this._Ophaalhuisnummer != value))
				{
					this._Ophaalhuisnummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ophaalplaats", DbType="NVarChar(MAX)")]
		public string Ophaalplaats
		{
			get
			{
				return this._Ophaalplaats;
			}
			set
			{
				if ((this._Ophaalplaats != value))
				{
					this._Ophaalplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ophaalland", DbType="NVarChar(MAX)")]
		public string Ophaalland
		{
			get
			{
				return this._Ophaalland;
			}
			set
			{
				if ((this._Ophaalland != value))
				{
					this._Ophaalland = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeur", DbType="Bit NOT NULL")]
		public bool IsChauffeur
		{
			get
			{
				return this._IsChauffeur;
			}
			set
			{
				if ((this._IsChauffeur != value))
				{
					this._IsChauffeur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurMa", DbType="Bit NOT NULL")]
		public bool IsChauffeurMa
		{
			get
			{
				return this._IsChauffeurMa;
			}
			set
			{
				if ((this._IsChauffeurMa != value))
				{
					this._IsChauffeurMa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurDi", DbType="Bit NOT NULL")]
		public bool IsChauffeurDi
		{
			get
			{
				return this._IsChauffeurDi;
			}
			set
			{
				if ((this._IsChauffeurDi != value))
				{
					this._IsChauffeurDi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurWo", DbType="Bit NOT NULL")]
		public bool IsChauffeurWo
		{
			get
			{
				return this._IsChauffeurWo;
			}
			set
			{
				if ((this._IsChauffeurWo != value))
				{
					this._IsChauffeurWo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurDo", DbType="Bit NOT NULL")]
		public bool IsChauffeurDo
		{
			get
			{
				return this._IsChauffeurDo;
			}
			set
			{
				if ((this._IsChauffeurDo != value))
				{
					this._IsChauffeurDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurVr", DbType="Bit NOT NULL")]
		public bool IsChauffeurVr
		{
			get
			{
				return this._IsChauffeurVr;
			}
			set
			{
				if ((this._IsChauffeurVr != value))
				{
					this._IsChauffeurVr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurZa", DbType="Bit NOT NULL")]
		public bool IsChauffeurZa
		{
			get
			{
				return this._IsChauffeurZa;
			}
			set
			{
				if ((this._IsChauffeurZa != value))
				{
					this._IsChauffeurZa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChauffeurZo", DbType="Bit NOT NULL")]
		public bool IsChauffeurZo
		{
			get
			{
				return this._IsChauffeurZo;
			}
			set
			{
				if ((this._IsChauffeurZo != value))
				{
					this._IsChauffeurZo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijder", DbType="Bit NOT NULL")]
		public bool IsBijrijder
		{
			get
			{
				return this._IsBijrijder;
			}
			set
			{
				if ((this._IsBijrijder != value))
				{
					this._IsBijrijder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijderMa", DbType="Bit NOT NULL")]
		public bool IsBijrijderMa
		{
			get
			{
				return this._IsBijrijderMa;
			}
			set
			{
				if ((this._IsBijrijderMa != value))
				{
					this._IsBijrijderMa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijderDi", DbType="Bit NOT NULL")]
		public bool IsBijrijderDi
		{
			get
			{
				return this._IsBijrijderDi;
			}
			set
			{
				if ((this._IsBijrijderDi != value))
				{
					this._IsBijrijderDi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijderWo", DbType="Bit NOT NULL")]
		public bool IsBijrijderWo
		{
			get
			{
				return this._IsBijrijderWo;
			}
			set
			{
				if ((this._IsBijrijderWo != value))
				{
					this._IsBijrijderWo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijderDo", DbType="Bit NOT NULL")]
		public bool IsBijrijderDo
		{
			get
			{
				return this._IsBijrijderDo;
			}
			set
			{
				if ((this._IsBijrijderDo != value))
				{
					this._IsBijrijderDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijderVr", DbType="Bit NOT NULL")]
		public bool IsBijrijderVr
		{
			get
			{
				return this._IsBijrijderVr;
			}
			set
			{
				if ((this._IsBijrijderVr != value))
				{
					this._IsBijrijderVr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijderZa", DbType="Bit NOT NULL")]
		public bool IsBijrijderZa
		{
			get
			{
				return this._IsBijrijderZa;
			}
			set
			{
				if ((this._IsBijrijderZa != value))
				{
					this._IsBijrijderZa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBijrijderZo", DbType="Bit NOT NULL")]
		public bool IsBijrijderZo
		{
			get
			{
				return this._IsBijrijderZo;
			}
			set
			{
				if ((this._IsBijrijderZo != value))
				{
					this._IsBijrijderZo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kenteken", DbType="NVarChar(50)")]
		public string Kenteken
		{
			get
			{
				return this._Kenteken;
			}
			set
			{
				if ((this._Kenteken != value))
				{
					this._Kenteken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this._Ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Di", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Di
		{
			get
			{
				return this._Di;
			}
			set
			{
				if ((this._Di != value))
				{
					this._Di = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wo", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Wo
		{
			get
			{
				return this._Wo;
			}
			set
			{
				if ((this._Wo != value))
				{
					this._Wo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Do", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Do
		{
			get
			{
				return this._Do;
			}
			set
			{
				if ((this._Do != value))
				{
					this._Do = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vr", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Vr
		{
			get
			{
				return this._Vr;
			}
			set
			{
				if ((this._Vr != value))
				{
					this._Vr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Za", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Za
		{
			get
			{
				return this._Za;
			}
			set
			{
				if ((this._Za != value))
				{
					this._Za = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zo", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Zo
		{
			get
			{
				return this._Zo;
			}
			set
			{
				if ((this._Zo != value))
				{
					this._Zo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Werkweek", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Werkweek
		{
			get
			{
				return this._Werkweek;
			}
			set
			{
				if ((this._Werkweek != value))
				{
					this._Werkweek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultBeginuur", DbType="Int")]
		public System.Nullable<int> DefaultBeginuur
		{
			get
			{
				return this._DefaultBeginuur;
			}
			set
			{
				if ((this._DefaultBeginuur != value))
				{
					this._DefaultBeginuur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultBeginminuut", DbType="Int")]
		public System.Nullable<int> DefaultBeginminuut
		{
			get
			{
				return this._DefaultBeginminuut;
			}
			set
			{
				if ((this._DefaultBeginminuut != value))
				{
					this._DefaultBeginminuut = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gebruiker")]
	public partial class Gebruiker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GebruikerId;
		
		private string _Gebruikersnaam;
		
		private string _Windowsidentity;
		
		private int _Gebruikersrol;
		
		private int _ProjectleiderId;
		
		private bool _IsProjectleider;
		
		private bool _CanLoginAsProjectleider;
		
		private bool _IsAdministrator;
		
		private int _ContactIdOrigineel;
		
		private int _PersoonNrOrigineel;
		
		private bool _CanPrint;
		
		private bool _IsManager;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGebruikerIdChanging(int value);
    partial void OnGebruikerIdChanged();
    partial void OnGebruikersnaamChanging(string value);
    partial void OnGebruikersnaamChanged();
    partial void OnWindowsidentityChanging(string value);
    partial void OnWindowsidentityChanged();
    partial void OnGebruikersrolChanging(int value);
    partial void OnGebruikersrolChanged();
    partial void OnProjectleiderIdChanging(int value);
    partial void OnProjectleiderIdChanged();
    partial void OnIsProjectleiderChanging(bool value);
    partial void OnIsProjectleiderChanged();
    partial void OnCanLoginAsProjectleiderChanging(bool value);
    partial void OnCanLoginAsProjectleiderChanged();
    partial void OnIsAdministratorChanging(bool value);
    partial void OnIsAdministratorChanged();
    partial void OnContactIdOrigineelChanging(int value);
    partial void OnContactIdOrigineelChanged();
    partial void OnPersoonNrOrigineelChanging(int value);
    partial void OnPersoonNrOrigineelChanged();
    partial void OnCanPrintChanging(bool value);
    partial void OnCanPrintChanged();
    partial void OnIsManagerChanging(bool value);
    partial void OnIsManagerChanged();
    #endregion
		
		public Gebruiker()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GebruikerId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int GebruikerId
		{
			get
			{
				return this._GebruikerId;
			}
			set
			{
				if ((this._GebruikerId != value))
				{
					this.OnGebruikerIdChanging(value);
					this.SendPropertyChanging();
					this._GebruikerId = value;
					this.SendPropertyChanged("GebruikerId");
					this.OnGebruikerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gebruikersnaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Gebruikersnaam
		{
			get
			{
				return this._Gebruikersnaam;
			}
			set
			{
				if ((this._Gebruikersnaam != value))
				{
					this.OnGebruikersnaamChanging(value);
					this.SendPropertyChanging();
					this._Gebruikersnaam = value;
					this.SendPropertyChanged("Gebruikersnaam");
					this.OnGebruikersnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Windowsidentity", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Windowsidentity
		{
			get
			{
				return this._Windowsidentity;
			}
			set
			{
				if ((this._Windowsidentity != value))
				{
					this.OnWindowsidentityChanging(value);
					this.SendPropertyChanging();
					this._Windowsidentity = value;
					this.SendPropertyChanged("Windowsidentity");
					this.OnWindowsidentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gebruikersrol", DbType="Int NOT NULL")]
		public int Gebruikersrol
		{
			get
			{
				return this._Gebruikersrol;
			}
			set
			{
				if ((this._Gebruikersrol != value))
				{
					this.OnGebruikersrolChanging(value);
					this.SendPropertyChanging();
					this._Gebruikersrol = value;
					this.SendPropertyChanged("Gebruikersrol");
					this.OnGebruikersrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectleiderId", DbType="Int NOT NULL")]
		public int ProjectleiderId
		{
			get
			{
				return this._ProjectleiderId;
			}
			set
			{
				if ((this._ProjectleiderId != value))
				{
					this.OnProjectleiderIdChanging(value);
					this.SendPropertyChanging();
					this._ProjectleiderId = value;
					this.SendPropertyChanged("ProjectleiderId");
					this.OnProjectleiderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProjectleider", DbType="Bit NOT NULL")]
		public bool IsProjectleider
		{
			get
			{
				return this._IsProjectleider;
			}
			set
			{
				if ((this._IsProjectleider != value))
				{
					this.OnIsProjectleiderChanging(value);
					this.SendPropertyChanging();
					this._IsProjectleider = value;
					this.SendPropertyChanged("IsProjectleider");
					this.OnIsProjectleiderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanLoginAsProjectleider", DbType="Bit NOT NULL")]
		public bool CanLoginAsProjectleider
		{
			get
			{
				return this._CanLoginAsProjectleider;
			}
			set
			{
				if ((this._CanLoginAsProjectleider != value))
				{
					this.OnCanLoginAsProjectleiderChanging(value);
					this.SendPropertyChanging();
					this._CanLoginAsProjectleider = value;
					this.SendPropertyChanged("CanLoginAsProjectleider");
					this.OnCanLoginAsProjectleiderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdministrator", DbType="Bit NOT NULL")]
		public bool IsAdministrator
		{
			get
			{
				return this._IsAdministrator;
			}
			set
			{
				if ((this._IsAdministrator != value))
				{
					this.OnIsAdministratorChanging(value);
					this.SendPropertyChanging();
					this._IsAdministrator = value;
					this.SendPropertyChanged("IsAdministrator");
					this.OnIsAdministratorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactIdOrigineel", DbType="Int NOT NULL")]
		public int ContactIdOrigineel
		{
			get
			{
				return this._ContactIdOrigineel;
			}
			set
			{
				if ((this._ContactIdOrigineel != value))
				{
					this.OnContactIdOrigineelChanging(value);
					this.SendPropertyChanging();
					this._ContactIdOrigineel = value;
					this.SendPropertyChanged("ContactIdOrigineel");
					this.OnContactIdOrigineelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersoonNrOrigineel", DbType="Int NOT NULL")]
		public int PersoonNrOrigineel
		{
			get
			{
				return this._PersoonNrOrigineel;
			}
			set
			{
				if ((this._PersoonNrOrigineel != value))
				{
					this.OnPersoonNrOrigineelChanging(value);
					this.SendPropertyChanging();
					this._PersoonNrOrigineel = value;
					this.SendPropertyChanged("PersoonNrOrigineel");
					this.OnPersoonNrOrigineelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanPrint", DbType="Bit NOT NULL")]
		public bool CanPrint
		{
			get
			{
				return this._CanPrint;
			}
			set
			{
				if ((this._CanPrint != value))
				{
					this.OnCanPrintChanging(value);
					this.SendPropertyChanging();
					this._CanPrint = value;
					this.SendPropertyChanged("CanPrint");
					this.OnCanPrintChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsManager", DbType="Bit NOT NULL")]
		public bool IsManager
		{
			get
			{
				return this._IsManager;
			}
			set
			{
				if ((this._IsManager != value))
				{
					this.OnIsManagerChanging(value);
					this.SendPropertyChanging();
					this._IsManager = value;
					this.SendPropertyChanged("IsManager");
					this.OnIsManagerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loonkosten")]
	public partial class Loonkosten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Persoon_Id;
		
		private System.DateTime _Vanaf;
		
		private string _Achternaam;
		
		private string _Voornaam;
		
		private decimal _KostPrijs_Dag;
		
		private decimal _KostPrijs_Uur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersoon_IdChanging(int value);
    partial void OnPersoon_IdChanged();
    partial void OnVanafChanging(System.DateTime value);
    partial void OnVanafChanged();
    partial void OnAchternaamChanging(string value);
    partial void OnAchternaamChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    partial void OnKostPrijs_DagChanging(decimal value);
    partial void OnKostPrijs_DagChanged();
    partial void OnKostPrijs_UurChanging(decimal value);
    partial void OnKostPrijs_UurChanged();
    #endregion
		
		public Loonkosten()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persoon_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Persoon_Id
		{
			get
			{
				return this._Persoon_Id;
			}
			set
			{
				if ((this._Persoon_Id != value))
				{
					this.OnPersoon_IdChanging(value);
					this.SendPropertyChanging();
					this._Persoon_Id = value;
					this.SendPropertyChanged("Persoon_Id");
					this.OnPersoon_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vanaf", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Vanaf
		{
			get
			{
				return this._Vanaf;
			}
			set
			{
				if ((this._Vanaf != value))
				{
					this.OnVanafChanging(value);
					this.SendPropertyChanging();
					this._Vanaf = value;
					this.SendPropertyChanged("Vanaf");
					this.OnVanafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this.OnAchternaamChanging(value);
					this.SendPropertyChanging();
					this._Achternaam = value;
					this.SendPropertyChanged("Achternaam");
					this.OnAchternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KostPrijs_Dag", DbType="Decimal(6,2) NOT NULL")]
		public decimal KostPrijs_Dag
		{
			get
			{
				return this._KostPrijs_Dag;
			}
			set
			{
				if ((this._KostPrijs_Dag != value))
				{
					this.OnKostPrijs_DagChanging(value);
					this.SendPropertyChanging();
					this._KostPrijs_Dag = value;
					this.SendPropertyChanged("KostPrijs_Dag");
					this.OnKostPrijs_DagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KostPrijs_Uur", DbType="Decimal(6,2) NOT NULL")]
		public decimal KostPrijs_Uur
		{
			get
			{
				return this._KostPrijs_Uur;
			}
			set
			{
				if ((this._KostPrijs_Uur != value))
				{
					this.OnKostPrijs_UurChanging(value);
					this.SendPropertyChanging();
					this._KostPrijs_Uur = value;
					this.SendPropertyChanged("KostPrijs_Uur");
					this.OnKostPrijs_UurChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwVakmanRelaties")]
	public partial class vwVakmanRelaty
	{
		
		private int _VakmanID;
		
		private System.Nullable<int> _PersoonNR;
		
		private string _PersoonNaam;
		
		private System.Nullable<int> _BedrijfNR;
		
		private string _BedrijfNaam;
		
		private bool _Intern;
		
		private System.Nullable<bool> _ZZP;
		
		private string _ArbeidsRelatie;
		
		private string _Contract;
		
		private string _Functie;
		
		private string _KetenPartner;
		
		private System.Nullable<System.DateTime> _Start;
		
		private System.Nullable<System.DateTime> _Eind;
		
		public vwVakmanRelaty()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VakmanID", DbType="Int NOT NULL")]
		public int VakmanID
		{
			get
			{
				return this._VakmanID;
			}
			set
			{
				if ((this._VakmanID != value))
				{
					this._VakmanID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersoonNR", DbType="Int")]
		public System.Nullable<int> PersoonNR
		{
			get
			{
				return this._PersoonNR;
			}
			set
			{
				if ((this._PersoonNR != value))
				{
					this._PersoonNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersoonNaam", DbType="NVarChar(152)")]
		public string PersoonNaam
		{
			get
			{
				return this._PersoonNaam;
			}
			set
			{
				if ((this._PersoonNaam != value))
				{
					this._PersoonNaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedrijfNR", DbType="Int")]
		public System.Nullable<int> BedrijfNR
		{
			get
			{
				return this._BedrijfNR;
			}
			set
			{
				if ((this._BedrijfNR != value))
				{
					this._BedrijfNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedrijfNaam", DbType="NVarChar(150)")]
		public string BedrijfNaam
		{
			get
			{
				return this._BedrijfNaam;
			}
			set
			{
				if ((this._BedrijfNaam != value))
				{
					this._BedrijfNaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intern", DbType="Bit NOT NULL")]
		public bool Intern
		{
			get
			{
				return this._Intern;
			}
			set
			{
				if ((this._Intern != value))
				{
					this._Intern = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZZP", DbType="Bit")]
		public System.Nullable<bool> ZZP
		{
			get
			{
				return this._ZZP;
			}
			set
			{
				if ((this._ZZP != value))
				{
					this._ZZP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArbeidsRelatie", DbType="VarChar(30)")]
		public string ArbeidsRelatie
		{
			get
			{
				return this._ArbeidsRelatie;
			}
			set
			{
				if ((this._ArbeidsRelatie != value))
				{
					this._ArbeidsRelatie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contract", DbType="VarChar(30)")]
		public string Contract
		{
			get
			{
				return this._Contract;
			}
			set
			{
				if ((this._Contract != value))
				{
					this._Contract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Functie", DbType="VarChar(30)")]
		public string Functie
		{
			get
			{
				return this._Functie;
			}
			set
			{
				if ((this._Functie != value))
				{
					this._Functie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetenPartner", DbType="VarChar(30)")]
		public string KetenPartner
		{
			get
			{
				return this._KetenPartner;
			}
			set
			{
				if ((this._KetenPartner != value))
				{
					this._KetenPartner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start", DbType="DateTime")]
		public System.Nullable<System.DateTime> Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this._Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eind", DbType="DateTime")]
		public System.Nullable<System.DateTime> Eind
		{
			get
			{
				return this._Eind;
			}
			set
			{
				if ((this._Eind != value))
				{
					this._Eind = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
