<?xml version="1.0" encoding="utf-8"?><Database Name="MandagenRegistratie" Class="dbLMandagenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MARINO-LAPTOP\SQLEXPRESS;Initial Catalog=MandagenRegistratie;Integrated Security=True" SettingsObjectName="MDR2PDF.Properties.Settings" SettingsPropertyName="MandagenRegistratieConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mandagen" Member="Mandagens">
    <Type Name="Mandagen">
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VakmanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VakmanstatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Begintijd" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Eindtijd" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Uren" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Minuten" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UrenGewijzigd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinutenGewijzigd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VakmansoortId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectleiderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Geannulleerd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Gewijzigd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Bevestigd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Bevestigingsdatum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsChauffeurHeen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurTerug" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KentekenHeen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KentekenTerug" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Definitief" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Mutatiedatum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MutatieDoorProjectleiderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vakman" Member="Vakmans">
    <Type Name="Vakman">
      <Column Name="VakmanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactIdOrigineel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BedrijfId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Actief" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Intern" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ZZP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Bsn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loonkosten" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="[Var]" Member="Var" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Kvk" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProjectleiderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Huisnummer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Plaats" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Land" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ophaaladres" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ophaalpostcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ophaalhuisnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ophaalplaats" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ophaalland" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsChauffeur" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurMa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurDi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurWo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurDo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurVr" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurZa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChauffeurZo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijderMa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijderDi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijderWo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijderDo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijderVr" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijderZa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBijrijderZo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Kenteken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ma" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Di" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Wo" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Do" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Vr" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Za" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Zo" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Werkweek" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="DefaultBeginuur" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DefaultBeginminuut" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gebruiker" Member="Gebruikers">
    <Type Name="Gebruiker">
      <Column Name="GebruikerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Gebruikersnaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Windowsidentity" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gebruikersrol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectleiderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsProjectleider" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanLoginAsProjectleider" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ContactIdOrigineel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PersoonNrOrigineel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CanPrint" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsManager" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Loonkosten" Member="Loonkostens">
    <Type Name="Loonkosten">
      <Column Name="Persoon_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Vanaf" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Achternaam" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Voornaam" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KostPrijs_Dag" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="KostPrijs_Uur" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vwVakmanRelaties" Member="vwVakmanRelaties">
    <Type Name="vwVakmanRelaty">
      <Column Name="VakmanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PersoonNR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersoonNaam" Type="System.String" DbType="NVarChar(152)" CanBeNull="true" />
      <Column Name="BedrijfNR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BedrijfNaam" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Intern" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ZZP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ArbeidsRelatie" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Contract" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Functie" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="KetenPartner" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Eind" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>