#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR2PDF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ZeebregtsDB")]
	public partial class dbLZeebregtsDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbLZeebregtsDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLZeebregtsDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLZeebregtsDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLZeebregtsDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<adressen> adressens
		{
			get
			{
				return this.GetTable<adressen>();
			}
		}
		
		public System.Data.Linq.Table<bedrijf> bedrijfs
		{
			get
			{
				return this.GetTable<bedrijf>();
			}
		}
		
		public System.Data.Linq.Table<persoon> persoons
		{
			get
			{
				return this.GetTable<persoon>();
			}
		}
		
		public System.Data.Linq.Table<project> projects
		{
			get
			{
				return this.GetTable<project>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.adressen")]
	public partial class adressen
	{
		
		private int _adres_id;
		
		private string _land;
		
		private string _plaats;
		
		private string _straat_1;
		
		private string _straat_2;
		
		private System.Nullable<int> _postcode_cijfers;
		
		private string _postcode_letters;
		
		private string _huis_postbus_nummer;
		
		private string _huisnummer_toevoeging;
		
		private bool _valid;
		
		private bool _via_postcode;
		
		public adressen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id", DbType="Int NOT NULL")]
		public int adres_id
		{
			get
			{
				return this._adres_id;
			}
			set
			{
				if ((this._adres_id != value))
				{
					this._adres_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_land", DbType="NVarChar(50)")]
		public string land
		{
			get
			{
				return this._land;
			}
			set
			{
				if ((this._land != value))
				{
					this._land = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaats", DbType="NVarChar(50)")]
		public string plaats
		{
			get
			{
				return this._plaats;
			}
			set
			{
				if ((this._plaats != value))
				{
					this._plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_straat_1", DbType="NVarChar(100)")]
		public string straat_1
		{
			get
			{
				return this._straat_1;
			}
			set
			{
				if ((this._straat_1 != value))
				{
					this._straat_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_straat_2", DbType="NVarChar(100)")]
		public string straat_2
		{
			get
			{
				return this._straat_2;
			}
			set
			{
				if ((this._straat_2 != value))
				{
					this._straat_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode_cijfers", DbType="Int")]
		public System.Nullable<int> postcode_cijfers
		{
			get
			{
				return this._postcode_cijfers;
			}
			set
			{
				if ((this._postcode_cijfers != value))
				{
					this._postcode_cijfers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode_letters", DbType="NVarChar(2)")]
		public string postcode_letters
		{
			get
			{
				return this._postcode_letters;
			}
			set
			{
				if ((this._postcode_letters != value))
				{
					this._postcode_letters = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huis_postbus_nummer", DbType="NVarChar(50)")]
		public string huis_postbus_nummer
		{
			get
			{
				return this._huis_postbus_nummer;
			}
			set
			{
				if ((this._huis_postbus_nummer != value))
				{
					this._huis_postbus_nummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huisnummer_toevoeging", DbType="NVarChar(50)")]
		public string huisnummer_toevoeging
		{
			get
			{
				return this._huisnummer_toevoeging;
			}
			set
			{
				if ((this._huisnummer_toevoeging != value))
				{
					this._huisnummer_toevoeging = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valid", DbType="Bit NOT NULL")]
		public bool valid
		{
			get
			{
				return this._valid;
			}
			set
			{
				if ((this._valid != value))
				{
					this._valid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_via_postcode", DbType="Bit NOT NULL")]
		public bool via_postcode
		{
			get
			{
				return this._via_postcode;
			}
			set
			{
				if ((this._via_postcode != value))
				{
					this._via_postcode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bedrijf")]
	public partial class bedrijf
	{
		
		private int _bedrijf_ID;
		
		private System.Nullable<int> _bedrijf_nr;
		
		private string _naam;
		
		private string _zoeknaam;
		
		private string _straat;
		
		private string _postcode;
		
		private string _plaats;
		
		private string _postSTRAAT;
		
		private string _postPOSTCODE;
		
		private string _postPLAATS;
		
		private string _tel;
		
		private string _mobiel;
		
		private string _fax;
		
		private string _email;
		
		private string _website;
		
		private string _bank;
		
		private string _Grek;
		
		private string _kvk;
		
		private System.Nullable<System.DateTime> _kvkUITGIFTE;
		
		private string _kvkSCAN;
		
		private string _omzetbelastingnr;
		
		private string _loonbelastingnr;
		
		private string _bedrijfverenigingnr;
		
		private System.Nullable<bool> _NIETactief;
		
		private string _IBAN;
		
		private string _SWIFT;
		
		private string _debiteurNRzeebregts;
		
		private string _crediteurNRzeebregts;
		
		private string _kostenplaats;
		
		private System.Nullable<bool> _postVIApostbus;
		
		private System.Nullable<int> _adres_id_bezoek;
		
		private System.Nullable<int> _adres_id_post;
		
		private string _telefoon_nr_settings;
		
		private string _telefoon_nr_1;
		
		private string _telefoon_nr_2;
		
		private string _telefoon_nr_3;
		
		private string _functie_omschrijving;
		
		public bedrijf()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijf_ID", DbType="Int NOT NULL")]
		public int bedrijf_ID
		{
			get
			{
				return this._bedrijf_ID;
			}
			set
			{
				if ((this._bedrijf_ID != value))
				{
					this._bedrijf_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijf_nr", DbType="Int")]
		public System.Nullable<int> bedrijf_nr
		{
			get
			{
				return this._bedrijf_nr;
			}
			set
			{
				if ((this._bedrijf_nr != value))
				{
					this._bedrijf_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="NVarChar(150)")]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this._naam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zoeknaam", DbType="NVarChar(52)")]
		public string zoeknaam
		{
			get
			{
				return this._zoeknaam;
			}
			set
			{
				if ((this._zoeknaam != value))
				{
					this._zoeknaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_straat", DbType="NVarChar(50)")]
		public string straat
		{
			get
			{
				return this._straat;
			}
			set
			{
				if ((this._straat != value))
				{
					this._straat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode", DbType="NVarChar(50)")]
		public string postcode
		{
			get
			{
				return this._postcode;
			}
			set
			{
				if ((this._postcode != value))
				{
					this._postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaats", DbType="NVarChar(50)")]
		public string plaats
		{
			get
			{
				return this._plaats;
			}
			set
			{
				if ((this._plaats != value))
				{
					this._plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postSTRAAT", DbType="NVarChar(255)")]
		public string postSTRAAT
		{
			get
			{
				return this._postSTRAAT;
			}
			set
			{
				if ((this._postSTRAAT != value))
				{
					this._postSTRAAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postPOSTCODE", DbType="NVarChar(50)")]
		public string postPOSTCODE
		{
			get
			{
				return this._postPOSTCODE;
			}
			set
			{
				if ((this._postPOSTCODE != value))
				{
					this._postPOSTCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postPLAATS", DbType="NVarChar(50)")]
		public string postPLAATS
		{
			get
			{
				return this._postPLAATS;
			}
			set
			{
				if ((this._postPLAATS != value))
				{
					this._postPLAATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(50)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this._tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobiel", DbType="NVarChar(50)")]
		public string mobiel
		{
			get
			{
				return this._mobiel;
			}
			set
			{
				if ((this._mobiel != value))
				{
					this._mobiel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(50)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this._fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(50)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this._website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bank", DbType="NVarChar(175)")]
		public string bank
		{
			get
			{
				return this._bank;
			}
			set
			{
				if ((this._bank != value))
				{
					this._bank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grek", DbType="NVarChar(50)")]
		public string Grek
		{
			get
			{
				return this._Grek;
			}
			set
			{
				if ((this._Grek != value))
				{
					this._Grek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kvk", DbType="NVarChar(50)")]
		public string kvk
		{
			get
			{
				return this._kvk;
			}
			set
			{
				if ((this._kvk != value))
				{
					this._kvk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kvkUITGIFTE", DbType="DateTime")]
		public System.Nullable<System.DateTime> kvkUITGIFTE
		{
			get
			{
				return this._kvkUITGIFTE;
			}
			set
			{
				if ((this._kvkUITGIFTE != value))
				{
					this._kvkUITGIFTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kvkSCAN", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string kvkSCAN
		{
			get
			{
				return this._kvkSCAN;
			}
			set
			{
				if ((this._kvkSCAN != value))
				{
					this._kvkSCAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_omzetbelastingnr", DbType="NVarChar(50)")]
		public string omzetbelastingnr
		{
			get
			{
				return this._omzetbelastingnr;
			}
			set
			{
				if ((this._omzetbelastingnr != value))
				{
					this._omzetbelastingnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loonbelastingnr", DbType="NVarChar(255)")]
		public string loonbelastingnr
		{
			get
			{
				return this._loonbelastingnr;
			}
			set
			{
				if ((this._loonbelastingnr != value))
				{
					this._loonbelastingnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijfverenigingnr", DbType="NVarChar(255)")]
		public string bedrijfverenigingnr
		{
			get
			{
				return this._bedrijfverenigingnr;
			}
			set
			{
				if ((this._bedrijfverenigingnr != value))
				{
					this._bedrijfverenigingnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIETactief", DbType="Bit")]
		public System.Nullable<bool> NIETactief
		{
			get
			{
				return this._NIETactief;
			}
			set
			{
				if ((this._NIETactief != value))
				{
					this._NIETactief = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="NVarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this._IBAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWIFT", DbType="NVarChar(50)")]
		public string SWIFT
		{
			get
			{
				return this._SWIFT;
			}
			set
			{
				if ((this._SWIFT != value))
				{
					this._SWIFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_debiteurNRzeebregts", DbType="NVarChar(50)")]
		public string debiteurNRzeebregts
		{
			get
			{
				return this._debiteurNRzeebregts;
			}
			set
			{
				if ((this._debiteurNRzeebregts != value))
				{
					this._debiteurNRzeebregts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crediteurNRzeebregts", DbType="NVarChar(50)")]
		public string crediteurNRzeebregts
		{
			get
			{
				return this._crediteurNRzeebregts;
			}
			set
			{
				if ((this._crediteurNRzeebregts != value))
				{
					this._crediteurNRzeebregts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kostenplaats", DbType="NVarChar(50)")]
		public string kostenplaats
		{
			get
			{
				return this._kostenplaats;
			}
			set
			{
				if ((this._kostenplaats != value))
				{
					this._kostenplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postVIApostbus", DbType="Bit")]
		public System.Nullable<bool> postVIApostbus
		{
			get
			{
				return this._postVIApostbus;
			}
			set
			{
				if ((this._postVIApostbus != value))
				{
					this._postVIApostbus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_bezoek", DbType="Int")]
		public System.Nullable<int> adres_id_bezoek
		{
			get
			{
				return this._adres_id_bezoek;
			}
			set
			{
				if ((this._adres_id_bezoek != value))
				{
					this._adres_id_bezoek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_post", DbType="Int")]
		public System.Nullable<int> adres_id_post
		{
			get
			{
				return this._adres_id_post;
			}
			set
			{
				if ((this._adres_id_post != value))
				{
					this._adres_id_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_settings", DbType="NVarChar(50)")]
		public string telefoon_nr_settings
		{
			get
			{
				return this._telefoon_nr_settings;
			}
			set
			{
				if ((this._telefoon_nr_settings != value))
				{
					this._telefoon_nr_settings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_1", DbType="NVarChar(50)")]
		public string telefoon_nr_1
		{
			get
			{
				return this._telefoon_nr_1;
			}
			set
			{
				if ((this._telefoon_nr_1 != value))
				{
					this._telefoon_nr_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_2", DbType="NVarChar(50)")]
		public string telefoon_nr_2
		{
			get
			{
				return this._telefoon_nr_2;
			}
			set
			{
				if ((this._telefoon_nr_2 != value))
				{
					this._telefoon_nr_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_3", DbType="NVarChar(50)")]
		public string telefoon_nr_3
		{
			get
			{
				return this._telefoon_nr_3;
			}
			set
			{
				if ((this._telefoon_nr_3 != value))
				{
					this._telefoon_nr_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_functie_omschrijving", DbType="NVarChar(255)")]
		public string functie_omschrijving
		{
			get
			{
				return this._functie_omschrijving;
			}
			set
			{
				if ((this._functie_omschrijving != value))
				{
					this._functie_omschrijving = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.persoon")]
	public partial class persoon
	{
		
		private int _persoon_ID;
		
		private System.Nullable<int> _persoon_nr;
		
		private System.Nullable<int> _taak_id;
		
		private System.Nullable<int> _bedrijf_nr;
		
		private System.Nullable<bool> _man;
		
		private string _voorletters;
		
		private string _voornaam;
		
		private string _tussenvoegsel;
		
		private string _achternaam;
		
		private string _zamobiel;
		
		private string _zatelefoonvast;
		
		private string _zafax;
		
		private string _zaemail;
		
		private System.Nullable<System.DateTime> _geboortedatum;
		
		private string _vastevrijedag1;
		
		private string _vastevrijedag2;
		
		private string _vastevrijedag3;
		
		private System.Nullable<bool> _NIETactief;
		
		private System.Nullable<int> _adres_id;
		
		private string _telefoon_nr_settings;
		
		private string _telefoon_nr_1;
		
		private string _telefoon_nr_2;
		
		private string _telefoon_nr_3;
		
		public persoon()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persoon_ID", DbType="Int NOT NULL")]
		public int persoon_ID
		{
			get
			{
				return this._persoon_ID;
			}
			set
			{
				if ((this._persoon_ID != value))
				{
					this._persoon_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persoon_nr", DbType="Int")]
		public System.Nullable<int> persoon_nr
		{
			get
			{
				return this._persoon_nr;
			}
			set
			{
				if ((this._persoon_nr != value))
				{
					this._persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taak_id", DbType="Int")]
		public System.Nullable<int> taak_id
		{
			get
			{
				return this._taak_id;
			}
			set
			{
				if ((this._taak_id != value))
				{
					this._taak_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijf_nr", DbType="Int")]
		public System.Nullable<int> bedrijf_nr
		{
			get
			{
				return this._bedrijf_nr;
			}
			set
			{
				if ((this._bedrijf_nr != value))
				{
					this._bedrijf_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_man", DbType="Bit")]
		public System.Nullable<bool> man
		{
			get
			{
				return this._man;
			}
			set
			{
				if ((this._man != value))
				{
					this._man = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voorletters", DbType="NVarChar(50)")]
		public string voorletters
		{
			get
			{
				return this._voorletters;
			}
			set
			{
				if ((this._voorletters != value))
				{
					this._voorletters = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voornaam", DbType="NVarChar(50)")]
		public string voornaam
		{
			get
			{
				return this._voornaam;
			}
			set
			{
				if ((this._voornaam != value))
				{
					this._voornaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tussenvoegsel", DbType="NVarChar(50)")]
		public string tussenvoegsel
		{
			get
			{
				return this._tussenvoegsel;
			}
			set
			{
				if ((this._tussenvoegsel != value))
				{
					this._tussenvoegsel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achternaam", DbType="NVarChar(50)")]
		public string achternaam
		{
			get
			{
				return this._achternaam;
			}
			set
			{
				if ((this._achternaam != value))
				{
					this._achternaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zamobiel", DbType="NVarChar(50)")]
		public string zamobiel
		{
			get
			{
				return this._zamobiel;
			}
			set
			{
				if ((this._zamobiel != value))
				{
					this._zamobiel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zatelefoonvast", DbType="NVarChar(50)")]
		public string zatelefoonvast
		{
			get
			{
				return this._zatelefoonvast;
			}
			set
			{
				if ((this._zatelefoonvast != value))
				{
					this._zatelefoonvast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zafax", DbType="NVarChar(50)")]
		public string zafax
		{
			get
			{
				return this._zafax;
			}
			set
			{
				if ((this._zafax != value))
				{
					this._zafax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zaemail", DbType="NVarChar(50)")]
		public string zaemail
		{
			get
			{
				return this._zaemail;
			}
			set
			{
				if ((this._zaemail != value))
				{
					this._zaemail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geboortedatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> geboortedatum
		{
			get
			{
				return this._geboortedatum;
			}
			set
			{
				if ((this._geboortedatum != value))
				{
					this._geboortedatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vastevrijedag1", DbType="NVarChar(50)")]
		public string vastevrijedag1
		{
			get
			{
				return this._vastevrijedag1;
			}
			set
			{
				if ((this._vastevrijedag1 != value))
				{
					this._vastevrijedag1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vastevrijedag2", DbType="NVarChar(50)")]
		public string vastevrijedag2
		{
			get
			{
				return this._vastevrijedag2;
			}
			set
			{
				if ((this._vastevrijedag2 != value))
				{
					this._vastevrijedag2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vastevrijedag3", DbType="NVarChar(50)")]
		public string vastevrijedag3
		{
			get
			{
				return this._vastevrijedag3;
			}
			set
			{
				if ((this._vastevrijedag3 != value))
				{
					this._vastevrijedag3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIETactief", DbType="Bit")]
		public System.Nullable<bool> NIETactief
		{
			get
			{
				return this._NIETactief;
			}
			set
			{
				if ((this._NIETactief != value))
				{
					this._NIETactief = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id", DbType="Int")]
		public System.Nullable<int> adres_id
		{
			get
			{
				return this._adres_id;
			}
			set
			{
				if ((this._adres_id != value))
				{
					this._adres_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_settings", DbType="NVarChar(50)")]
		public string telefoon_nr_settings
		{
			get
			{
				return this._telefoon_nr_settings;
			}
			set
			{
				if ((this._telefoon_nr_settings != value))
				{
					this._telefoon_nr_settings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_1", DbType="NVarChar(50)")]
		public string telefoon_nr_1
		{
			get
			{
				return this._telefoon_nr_1;
			}
			set
			{
				if ((this._telefoon_nr_1 != value))
				{
					this._telefoon_nr_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_2", DbType="NVarChar(50)")]
		public string telefoon_nr_2
		{
			get
			{
				return this._telefoon_nr_2;
			}
			set
			{
				if ((this._telefoon_nr_2 != value))
				{
					this._telefoon_nr_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_3", DbType="NVarChar(50)")]
		public string telefoon_nr_3
		{
			get
			{
				return this._telefoon_nr_3;
			}
			set
			{
				if ((this._telefoon_nr_3 != value))
				{
					this._telefoon_nr_3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.project")]
	public partial class project
	{
		
		private int _project_ID;
		
		private System.Nullable<int> _project_NR;
		
		private System.Nullable<int> _hoofdproject_nr;
		
		private string _aannemer_projectnummer;
		
		private string _aannemer_contractnummer;
		
		private string _naam_project;
		
		private string _naam_specificatie;
		
		private System.Nullable<int> _opdrachtgeverZEEBREGTS_nr;
		
		private string _plaats;
		
		private string _aannemer;
		
		private System.Nullable<System.DateTime> _off_aanvraag;
		
		private System.Nullable<System.DateTime> _off_verstuurd;
		
		private System.Nullable<System.DateTime> _off_def;
		
		private System.Nullable<int> @__0off_volg;
		
		private System.Nullable<int> @__0off_versie;
		
		private System.Nullable<System.DateTime> @__0off_aanvraag;
		
		private System.Nullable<System.DateTime> @__0off_verstuurd;
		
		private string _nagebeld;
		
		private System.Nullable<System.DateTime> @__0off_def;
		
		private System.Nullable<double> _prov_vast_aan_;
		
		private System.Nullable<double> _prov_vast_aan_meerwerk_;
		
		private System.Nullable<int> _verekenmethode;
		
		private System.Nullable<float> _exel_master;
		
		private System.Nullable<int> _status;
		
		private string _administratieCHECK;
		
		private System.Nullable<int> _betalingstermijn;
		
		private System.Nullable<int> _verpakkenPER_0_offerte;
		
		private System.Nullable<decimal> _verpakkenper_vloer;
		
		private System.Nullable<decimal> _verpaken_per_wand;
		
		private System.Nullable<int> _index_;
		
		private System.Nullable<int> _garantie;
		
		private string _lijm;
		
		private System.Nullable<decimal> _stelpostwand;
		
		private System.Nullable<decimal> _stelpostvloer;
		
		private System.Nullable<double> _opslagprijs_koper;
		
		private System.Nullable<double> _opslagmeters_koper;
		
		private System.Nullable<System.DateTime> _deadline_0off;
		
		private System.Nullable<System.DateTime> _deadline_off;
		
		private System.Nullable<int> _verpVIAbestelling;
		
		private System.Nullable<System.DateTime> _start_check;
		
		private string _start_uitvoer;
		
		private System.Nullable<int> _planning_start_week;
		
		private System.Nullable<int> _planning_start_jaar;
		
		private System.Nullable<int> _planning_eind_week;
		
		private System.Nullable<int> _planning_eind_jaar;
		
		private System.Nullable<int> _bouw_snelheid;
		
		private string _bouw_straat;
		
		private string _bouw_postcode;
		
		private string _bouw_tel;
		
		private string _bouw_fax;
		
		private string _website;
		
		private bool _verkoopbrochure;
		
		private bool _NAWgegevens;
		
		private bool @__0_tekeningen;
		
		private System.Nullable<int> _FACTORnietAW_Zeebregts;
		
		private System.Nullable<int> _FACTORcorrectie_Offerte;
		
		private System.Nullable<double> _coordiatiekostenbouwbedrijf_;
		
		private System.Nullable<int> _switchcontract;
		
		private System.Nullable<int> _contact_leverancier_luxetegels;
		
		private System.Nullable<int> _contact_leverancier_hoekprofielen;
		
		private System.Nullable<int> _contact_leverancier_standaardtegels;
		
		private string _memo_aanvraag;
		
		private System.Nullable<int> _STABU_groep;
		
		private System.Nullable<bool> _STABU_groep_ja_nee;
		
		private string _nacalculatiecode;
		
		private System.Nullable<bool> _INafbouwCONTROL;
		
		private System.Nullable<int> _aantal_koopwoningen;
		
		private string _omschrijvingKoopwoningen;
		
		private string _factuur_aanhef;
		
		private string _factuur_adres;
		
		private string _factuur_postcode;
		
		private string _factuur_plaats;
		
		private bool _UITvia0offerte;
		
		private bool @__0off_aanv;
		
		private string @__0off_annv_omschrijving;
		
		private System.Nullable<int> _inkoper_nr;
		
		private System.Nullable<int> _werkvoorbereider_nr;
		
		private System.Nullable<int> _projectleider_nr;
		
		private System.Nullable<int> _uitvoerder_nr;
		
		private System.Nullable<int> _kopersbegeleider_nr;
		
		private System.Nullable<int> _contactpersoonTegelshowroom_nr;
		
		private System.Nullable<int> _contactpersoonSANITAIRshowroom_nr;
		
		private System.Nullable<int> _contactpersoonKEUKENshowroom_nr;
		
		private System.Nullable<int> _offerte_persoon_nr;
		
		private System.Nullable<int> @__0offerte_persoon_nr;
		
		private System.Nullable<int> _koperofferte_persoon_nr;
		
		private System.Nullable<int> _uitvoerderAfbouw_persoon_nr;
		
		private System.Nullable<int> _uitvoerderZeebregts_persoon_nr;
		
		private System.Nullable<int> _tegelzetter_persoon_nr;
		
		private System.Nullable<int> _opzichter_persoon_nr;
		
		private System.Nullable<int> _bouwbedrijf_nr;
		
		private System.Nullable<int> _kopersbegeleidingbedrijf_nr;
		
		private System.Nullable<int> _facturatieMEERWERKbedrijf_nr;
		
		private System.Nullable<int> _betalingbedrijf;
		
		private System.Nullable<int> _tegelshowroom_nr;
		
		private System.Nullable<int> _sanitairshowroom_nr;
		
		private System.Nullable<int> _keukenshowroom_nr;
		
		private System.Nullable<int> _projectontwikkelaar_nr;
		
		private System.Nullable<int> _showroom_PARTNER_NR;
		
		private System.Nullable<int> _leverancier_HOEKPROFIELEN;
		
		private System.Nullable<int> _leverancier_STANDAARD;
		
		private System.Nullable<int> _opdrachtgever_bestelling_partner_nr;
		
		private System.Nullable<bool> _verpakkingstoeslagUpgrade;
		
		private string _projectNRadminZeebregts;
		
		private System.Nullable<int> _adres_id_bouw;
		
		private System.Nullable<int> _adres_id_factuur;
		
		private string _telefoon_nr_1;
		
		private string _telefoon_nr_2;
		
		private string _telefoon_nr_3;
		
		private string _telefoon_nr_settings;
		
		private decimal _btw;
		
		public project()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_ID", DbType="Int NOT NULL")]
		public int project_ID
		{
			get
			{
				return this._project_ID;
			}
			set
			{
				if ((this._project_ID != value))
				{
					this._project_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_NR", DbType="Int")]
		public System.Nullable<int> project_NR
		{
			get
			{
				return this._project_NR;
			}
			set
			{
				if ((this._project_NR != value))
				{
					this._project_NR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoofdproject_nr", DbType="Int")]
		public System.Nullable<int> hoofdproject_nr
		{
			get
			{
				return this._hoofdproject_nr;
			}
			set
			{
				if ((this._hoofdproject_nr != value))
				{
					this._hoofdproject_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aannemer_projectnummer", DbType="NVarChar(50)")]
		public string aannemer_projectnummer
		{
			get
			{
				return this._aannemer_projectnummer;
			}
			set
			{
				if ((this._aannemer_projectnummer != value))
				{
					this._aannemer_projectnummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aannemer_contractnummer", DbType="NVarChar(50)")]
		public string aannemer_contractnummer
		{
			get
			{
				return this._aannemer_contractnummer;
			}
			set
			{
				if ((this._aannemer_contractnummer != value))
				{
					this._aannemer_contractnummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam_project", DbType="NVarChar(100)")]
		public string naam_project
		{
			get
			{
				return this._naam_project;
			}
			set
			{
				if ((this._naam_project != value))
				{
					this._naam_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam_specificatie", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string naam_specificatie
		{
			get
			{
				return this._naam_specificatie;
			}
			set
			{
				if ((this._naam_specificatie != value))
				{
					this._naam_specificatie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opdrachtgeverZEEBREGTS_nr", DbType="Int")]
		public System.Nullable<int> opdrachtgeverZEEBREGTS_nr
		{
			get
			{
				return this._opdrachtgeverZEEBREGTS_nr;
			}
			set
			{
				if ((this._opdrachtgeverZEEBREGTS_nr != value))
				{
					this._opdrachtgeverZEEBREGTS_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaats", DbType="NVarChar(50)")]
		public string plaats
		{
			get
			{
				return this._plaats;
			}
			set
			{
				if ((this._plaats != value))
				{
					this._plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aannemer", DbType="NVarChar(50)")]
		public string aannemer
		{
			get
			{
				return this._aannemer;
			}
			set
			{
				if ((this._aannemer != value))
				{
					this._aannemer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_off_aanvraag", DbType="DateTime")]
		public System.Nullable<System.DateTime> off_aanvraag
		{
			get
			{
				return this._off_aanvraag;
			}
			set
			{
				if ((this._off_aanvraag != value))
				{
					this._off_aanvraag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_off_verstuurd", DbType="DateTime")]
		public System.Nullable<System.DateTime> off_verstuurd
		{
			get
			{
				return this._off_verstuurd;
			}
			set
			{
				if ((this._off_verstuurd != value))
				{
					this._off_verstuurd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_off_def", DbType="DateTime")]
		public System.Nullable<System.DateTime> off_def
		{
			get
			{
				return this._off_def;
			}
			set
			{
				if ((this._off_def != value))
				{
					this._off_def = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0off_volg]", Storage="__0off_volg", DbType="Int")]
		public System.Nullable<int> _0off_volg
		{
			get
			{
				return this.@__0off_volg;
			}
			set
			{
				if ((this.@__0off_volg != value))
				{
					this.@__0off_volg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0off_versie]", Storage="__0off_versie", DbType="Int")]
		public System.Nullable<int> _0off_versie
		{
			get
			{
				return this.@__0off_versie;
			}
			set
			{
				if ((this.@__0off_versie != value))
				{
					this.@__0off_versie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0off_aanvraag]", Storage="__0off_aanvraag", DbType="DateTime")]
		public System.Nullable<System.DateTime> _0off_aanvraag
		{
			get
			{
				return this.@__0off_aanvraag;
			}
			set
			{
				if ((this.@__0off_aanvraag != value))
				{
					this.@__0off_aanvraag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0off_verstuurd]", Storage="__0off_verstuurd", DbType="DateTime")]
		public System.Nullable<System.DateTime> _0off_verstuurd
		{
			get
			{
				return this.@__0off_verstuurd;
			}
			set
			{
				if ((this.@__0off_verstuurd != value))
				{
					this.@__0off_verstuurd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nagebeld", DbType="NVarChar(50)")]
		public string nagebeld
		{
			get
			{
				return this._nagebeld;
			}
			set
			{
				if ((this._nagebeld != value))
				{
					this._nagebeld = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0off_def]", Storage="__0off_def", DbType="DateTime")]
		public System.Nullable<System.DateTime> _0off_def
		{
			get
			{
				return this.@__0off_def;
			}
			set
			{
				if ((this.@__0off_def != value))
				{
					this.@__0off_def = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[prov_vast_aan%]", Storage="_prov_vast_aan_", DbType="Float")]
		public System.Nullable<double> prov_vast_aan_
		{
			get
			{
				return this._prov_vast_aan_;
			}
			set
			{
				if ((this._prov_vast_aan_ != value))
				{
					this._prov_vast_aan_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[prov_vast_aan_meerwerk%]", Storage="_prov_vast_aan_meerwerk_", DbType="Float")]
		public System.Nullable<double> prov_vast_aan_meerwerk_
		{
			get
			{
				return this._prov_vast_aan_meerwerk_;
			}
			set
			{
				if ((this._prov_vast_aan_meerwerk_ != value))
				{
					this._prov_vast_aan_meerwerk_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verekenmethode", DbType="Int")]
		public System.Nullable<int> verekenmethode
		{
			get
			{
				return this._verekenmethode;
			}
			set
			{
				if ((this._verekenmethode != value))
				{
					this._verekenmethode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exel_master", DbType="Real")]
		public System.Nullable<float> exel_master
		{
			get
			{
				return this._exel_master;
			}
			set
			{
				if ((this._exel_master != value))
				{
					this._exel_master = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_administratieCHECK", DbType="NVarChar(50)")]
		public string administratieCHECK
		{
			get
			{
				return this._administratieCHECK;
			}
			set
			{
				if ((this._administratieCHECK != value))
				{
					this._administratieCHECK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betalingstermijn", DbType="Int")]
		public System.Nullable<int> betalingstermijn
		{
			get
			{
				return this._betalingstermijn;
			}
			set
			{
				if ((this._betalingstermijn != value))
				{
					this._betalingstermijn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verpakkenPER_0_offerte", DbType="Int")]
		public System.Nullable<int> verpakkenPER_0_offerte
		{
			get
			{
				return this._verpakkenPER_0_offerte;
			}
			set
			{
				if ((this._verpakkenPER_0_offerte != value))
				{
					this._verpakkenPER_0_offerte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verpakkenper_vloer", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> verpakkenper_vloer
		{
			get
			{
				return this._verpakkenper_vloer;
			}
			set
			{
				if ((this._verpakkenper_vloer != value))
				{
					this._verpakkenper_vloer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verpaken_per_wand", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> verpaken_per_wand
		{
			get
			{
				return this._verpaken_per_wand;
			}
			set
			{
				if ((this._verpaken_per_wand != value))
				{
					this._verpaken_per_wand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[index%]", Storage="_index_", DbType="Int")]
		public System.Nullable<int> index_
		{
			get
			{
				return this._index_;
			}
			set
			{
				if ((this._index_ != value))
				{
					this._index_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_garantie", DbType="Int")]
		public System.Nullable<int> garantie
		{
			get
			{
				return this._garantie;
			}
			set
			{
				if ((this._garantie != value))
				{
					this._garantie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lijm", DbType="NVarChar(50)")]
		public string lijm
		{
			get
			{
				return this._lijm;
			}
			set
			{
				if ((this._lijm != value))
				{
					this._lijm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stelpostwand", DbType="Money")]
		public System.Nullable<decimal> stelpostwand
		{
			get
			{
				return this._stelpostwand;
			}
			set
			{
				if ((this._stelpostwand != value))
				{
					this._stelpostwand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stelpostvloer", DbType="Money")]
		public System.Nullable<decimal> stelpostvloer
		{
			get
			{
				return this._stelpostvloer;
			}
			set
			{
				if ((this._stelpostvloer != value))
				{
					this._stelpostvloer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opslagprijs_koper", DbType="Float")]
		public System.Nullable<double> opslagprijs_koper
		{
			get
			{
				return this._opslagprijs_koper;
			}
			set
			{
				if ((this._opslagprijs_koper != value))
				{
					this._opslagprijs_koper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opslagmeters_koper", DbType="Float")]
		public System.Nullable<double> opslagmeters_koper
		{
			get
			{
				return this._opslagmeters_koper;
			}
			set
			{
				if ((this._opslagmeters_koper != value))
				{
					this._opslagmeters_koper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deadline_0off", DbType="DateTime")]
		public System.Nullable<System.DateTime> deadline_0off
		{
			get
			{
				return this._deadline_0off;
			}
			set
			{
				if ((this._deadline_0off != value))
				{
					this._deadline_0off = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deadline_off", DbType="DateTime")]
		public System.Nullable<System.DateTime> deadline_off
		{
			get
			{
				return this._deadline_off;
			}
			set
			{
				if ((this._deadline_off != value))
				{
					this._deadline_off = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verpVIAbestelling", DbType="Int")]
		public System.Nullable<int> verpVIAbestelling
		{
			get
			{
				return this._verpVIAbestelling;
			}
			set
			{
				if ((this._verpVIAbestelling != value))
				{
					this._verpVIAbestelling = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_check", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_check
		{
			get
			{
				return this._start_check;
			}
			set
			{
				if ((this._start_check != value))
				{
					this._start_check = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_uitvoer", DbType="NVarChar(50)")]
		public string start_uitvoer
		{
			get
			{
				return this._start_uitvoer;
			}
			set
			{
				if ((this._start_uitvoer != value))
				{
					this._start_uitvoer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planning_start_week", DbType="Int")]
		public System.Nullable<int> planning_start_week
		{
			get
			{
				return this._planning_start_week;
			}
			set
			{
				if ((this._planning_start_week != value))
				{
					this._planning_start_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planning_start_jaar", DbType="Int")]
		public System.Nullable<int> planning_start_jaar
		{
			get
			{
				return this._planning_start_jaar;
			}
			set
			{
				if ((this._planning_start_jaar != value))
				{
					this._planning_start_jaar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planning_eind_week", DbType="Int")]
		public System.Nullable<int> planning_eind_week
		{
			get
			{
				return this._planning_eind_week;
			}
			set
			{
				if ((this._planning_eind_week != value))
				{
					this._planning_eind_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planning_eind_jaar", DbType="Int")]
		public System.Nullable<int> planning_eind_jaar
		{
			get
			{
				return this._planning_eind_jaar;
			}
			set
			{
				if ((this._planning_eind_jaar != value))
				{
					this._planning_eind_jaar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bouw_snelheid", DbType="Int")]
		public System.Nullable<int> bouw_snelheid
		{
			get
			{
				return this._bouw_snelheid;
			}
			set
			{
				if ((this._bouw_snelheid != value))
				{
					this._bouw_snelheid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bouw_straat", DbType="NVarChar(250)")]
		public string bouw_straat
		{
			get
			{
				return this._bouw_straat;
			}
			set
			{
				if ((this._bouw_straat != value))
				{
					this._bouw_straat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bouw_postcode", DbType="NVarChar(50)")]
		public string bouw_postcode
		{
			get
			{
				return this._bouw_postcode;
			}
			set
			{
				if ((this._bouw_postcode != value))
				{
					this._bouw_postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bouw_tel", DbType="NVarChar(50)")]
		public string bouw_tel
		{
			get
			{
				return this._bouw_tel;
			}
			set
			{
				if ((this._bouw_tel != value))
				{
					this._bouw_tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bouw_fax", DbType="NVarChar(50)")]
		public string bouw_fax
		{
			get
			{
				return this._bouw_fax;
			}
			set
			{
				if ((this._bouw_fax != value))
				{
					this._bouw_fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(100)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this._website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verkoopbrochure", DbType="Bit NOT NULL")]
		public bool verkoopbrochure
		{
			get
			{
				return this._verkoopbrochure;
			}
			set
			{
				if ((this._verkoopbrochure != value))
				{
					this._verkoopbrochure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAWgegevens", DbType="Bit NOT NULL")]
		public bool NAWgegevens
		{
			get
			{
				return this._NAWgegevens;
			}
			set
			{
				if ((this._NAWgegevens != value))
				{
					this._NAWgegevens = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0_tekeningen]", Storage="__0_tekeningen", DbType="Bit NOT NULL")]
		public bool _0_tekeningen
		{
			get
			{
				return this.@__0_tekeningen;
			}
			set
			{
				if ((this.@__0_tekeningen != value))
				{
					this.@__0_tekeningen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACTORnietAW_Zeebregts", DbType="Int")]
		public System.Nullable<int> FACTORnietAW_Zeebregts
		{
			get
			{
				return this._FACTORnietAW_Zeebregts;
			}
			set
			{
				if ((this._FACTORnietAW_Zeebregts != value))
				{
					this._FACTORnietAW_Zeebregts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACTORcorrectie_Offerte", DbType="Int")]
		public System.Nullable<int> FACTORcorrectie_Offerte
		{
			get
			{
				return this._FACTORcorrectie_Offerte;
			}
			set
			{
				if ((this._FACTORcorrectie_Offerte != value))
				{
					this._FACTORcorrectie_Offerte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[coordiatiekostenbouwbedrijf%]", Storage="_coordiatiekostenbouwbedrijf_", DbType="Float")]
		public System.Nullable<double> coordiatiekostenbouwbedrijf_
		{
			get
			{
				return this._coordiatiekostenbouwbedrijf_;
			}
			set
			{
				if ((this._coordiatiekostenbouwbedrijf_ != value))
				{
					this._coordiatiekostenbouwbedrijf_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_switchcontract", DbType="Int")]
		public System.Nullable<int> switchcontract
		{
			get
			{
				return this._switchcontract;
			}
			set
			{
				if ((this._switchcontract != value))
				{
					this._switchcontract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_leverancier_luxetegels", DbType="Int")]
		public System.Nullable<int> contact_leverancier_luxetegels
		{
			get
			{
				return this._contact_leverancier_luxetegels;
			}
			set
			{
				if ((this._contact_leverancier_luxetegels != value))
				{
					this._contact_leverancier_luxetegels = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_leverancier_hoekprofielen", DbType="Int")]
		public System.Nullable<int> contact_leverancier_hoekprofielen
		{
			get
			{
				return this._contact_leverancier_hoekprofielen;
			}
			set
			{
				if ((this._contact_leverancier_hoekprofielen != value))
				{
					this._contact_leverancier_hoekprofielen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_leverancier_standaardtegels", DbType="Int")]
		public System.Nullable<int> contact_leverancier_standaardtegels
		{
			get
			{
				return this._contact_leverancier_standaardtegels;
			}
			set
			{
				if ((this._contact_leverancier_standaardtegels != value))
				{
					this._contact_leverancier_standaardtegels = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memo_aanvraag", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string memo_aanvraag
		{
			get
			{
				return this._memo_aanvraag;
			}
			set
			{
				if ((this._memo_aanvraag != value))
				{
					this._memo_aanvraag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STABU_groep", DbType="Int")]
		public System.Nullable<int> STABU_groep
		{
			get
			{
				return this._STABU_groep;
			}
			set
			{
				if ((this._STABU_groep != value))
				{
					this._STABU_groep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STABU_groep_ja/nee]", Storage="_STABU_groep_ja_nee", DbType="Bit")]
		public System.Nullable<bool> STABU_groep_ja_nee
		{
			get
			{
				return this._STABU_groep_ja_nee;
			}
			set
			{
				if ((this._STABU_groep_ja_nee != value))
				{
					this._STABU_groep_ja_nee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nacalculatiecode", DbType="NVarChar(50)")]
		public string nacalculatiecode
		{
			get
			{
				return this._nacalculatiecode;
			}
			set
			{
				if ((this._nacalculatiecode != value))
				{
					this._nacalculatiecode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INafbouwCONTROL", DbType="Bit")]
		public System.Nullable<bool> INafbouwCONTROL
		{
			get
			{
				return this._INafbouwCONTROL;
			}
			set
			{
				if ((this._INafbouwCONTROL != value))
				{
					this._INafbouwCONTROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aantal_koopwoningen", DbType="Int")]
		public System.Nullable<int> aantal_koopwoningen
		{
			get
			{
				return this._aantal_koopwoningen;
			}
			set
			{
				if ((this._aantal_koopwoningen != value))
				{
					this._aantal_koopwoningen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_omschrijvingKoopwoningen", DbType="NVarChar(100)")]
		public string omschrijvingKoopwoningen
		{
			get
			{
				return this._omschrijvingKoopwoningen;
			}
			set
			{
				if ((this._omschrijvingKoopwoningen != value))
				{
					this._omschrijvingKoopwoningen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factuur_aanhef", DbType="NVarChar(50)")]
		public string factuur_aanhef
		{
			get
			{
				return this._factuur_aanhef;
			}
			set
			{
				if ((this._factuur_aanhef != value))
				{
					this._factuur_aanhef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factuur_adres", DbType="NVarChar(50)")]
		public string factuur_adres
		{
			get
			{
				return this._factuur_adres;
			}
			set
			{
				if ((this._factuur_adres != value))
				{
					this._factuur_adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factuur_postcode", DbType="NVarChar(50)")]
		public string factuur_postcode
		{
			get
			{
				return this._factuur_postcode;
			}
			set
			{
				if ((this._factuur_postcode != value))
				{
					this._factuur_postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factuur_plaats", DbType="NVarChar(50)")]
		public string factuur_plaats
		{
			get
			{
				return this._factuur_plaats;
			}
			set
			{
				if ((this._factuur_plaats != value))
				{
					this._factuur_plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UITvia0offerte", DbType="Bit NOT NULL")]
		public bool UITvia0offerte
		{
			get
			{
				return this._UITvia0offerte;
			}
			set
			{
				if ((this._UITvia0offerte != value))
				{
					this._UITvia0offerte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0off_aanv]", Storage="__0off_aanv", DbType="Bit NOT NULL")]
		public bool _0off_aanv
		{
			get
			{
				return this.@__0off_aanv;
			}
			set
			{
				if ((this.@__0off_aanv != value))
				{
					this.@__0off_aanv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0off_annv_omschrijving]", Storage="__0off_annv_omschrijving", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string _0off_annv_omschrijving
		{
			get
			{
				return this.@__0off_annv_omschrijving;
			}
			set
			{
				if ((this.@__0off_annv_omschrijving != value))
				{
					this.@__0off_annv_omschrijving = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inkoper_nr", DbType="Int")]
		public System.Nullable<int> inkoper_nr
		{
			get
			{
				return this._inkoper_nr;
			}
			set
			{
				if ((this._inkoper_nr != value))
				{
					this._inkoper_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_werkvoorbereider_nr", DbType="Int")]
		public System.Nullable<int> werkvoorbereider_nr
		{
			get
			{
				return this._werkvoorbereider_nr;
			}
			set
			{
				if ((this._werkvoorbereider_nr != value))
				{
					this._werkvoorbereider_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectleider_nr", DbType="Int")]
		public System.Nullable<int> projectleider_nr
		{
			get
			{
				return this._projectleider_nr;
			}
			set
			{
				if ((this._projectleider_nr != value))
				{
					this._projectleider_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uitvoerder_nr", DbType="Int")]
		public System.Nullable<int> uitvoerder_nr
		{
			get
			{
				return this._uitvoerder_nr;
			}
			set
			{
				if ((this._uitvoerder_nr != value))
				{
					this._uitvoerder_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kopersbegeleider_nr", DbType="Int")]
		public System.Nullable<int> kopersbegeleider_nr
		{
			get
			{
				return this._kopersbegeleider_nr;
			}
			set
			{
				if ((this._kopersbegeleider_nr != value))
				{
					this._kopersbegeleider_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactpersoonTegelshowroom_nr", DbType="Int")]
		public System.Nullable<int> contactpersoonTegelshowroom_nr
		{
			get
			{
				return this._contactpersoonTegelshowroom_nr;
			}
			set
			{
				if ((this._contactpersoonTegelshowroom_nr != value))
				{
					this._contactpersoonTegelshowroom_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactpersoonSANITAIRshowroom_nr", DbType="Int")]
		public System.Nullable<int> contactpersoonSANITAIRshowroom_nr
		{
			get
			{
				return this._contactpersoonSANITAIRshowroom_nr;
			}
			set
			{
				if ((this._contactpersoonSANITAIRshowroom_nr != value))
				{
					this._contactpersoonSANITAIRshowroom_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactpersoonKEUKENshowroom_nr", DbType="Int")]
		public System.Nullable<int> contactpersoonKEUKENshowroom_nr
		{
			get
			{
				return this._contactpersoonKEUKENshowroom_nr;
			}
			set
			{
				if ((this._contactpersoonKEUKENshowroom_nr != value))
				{
					this._contactpersoonKEUKENshowroom_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offerte_persoon_nr", DbType="Int")]
		public System.Nullable<int> offerte_persoon_nr
		{
			get
			{
				return this._offerte_persoon_nr;
			}
			set
			{
				if ((this._offerte_persoon_nr != value))
				{
					this._offerte_persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0offerte_persoon_nr]", Storage="__0offerte_persoon_nr", DbType="Int")]
		public System.Nullable<int> _0offerte_persoon_nr
		{
			get
			{
				return this.@__0offerte_persoon_nr;
			}
			set
			{
				if ((this.@__0offerte_persoon_nr != value))
				{
					this.@__0offerte_persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_koperofferte_persoon_nr", DbType="Int")]
		public System.Nullable<int> koperofferte_persoon_nr
		{
			get
			{
				return this._koperofferte_persoon_nr;
			}
			set
			{
				if ((this._koperofferte_persoon_nr != value))
				{
					this._koperofferte_persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uitvoerderAfbouw_persoon_nr", DbType="Int")]
		public System.Nullable<int> uitvoerderAfbouw_persoon_nr
		{
			get
			{
				return this._uitvoerderAfbouw_persoon_nr;
			}
			set
			{
				if ((this._uitvoerderAfbouw_persoon_nr != value))
				{
					this._uitvoerderAfbouw_persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uitvoerderZeebregts_persoon_nr", DbType="Int")]
		public System.Nullable<int> uitvoerderZeebregts_persoon_nr
		{
			get
			{
				return this._uitvoerderZeebregts_persoon_nr;
			}
			set
			{
				if ((this._uitvoerderZeebregts_persoon_nr != value))
				{
					this._uitvoerderZeebregts_persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tegelzetter_persoon_nr", DbType="Int")]
		public System.Nullable<int> tegelzetter_persoon_nr
		{
			get
			{
				return this._tegelzetter_persoon_nr;
			}
			set
			{
				if ((this._tegelzetter_persoon_nr != value))
				{
					this._tegelzetter_persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[opzichter_persoon-nr]", Storage="_opzichter_persoon_nr", DbType="Int")]
		public System.Nullable<int> opzichter_persoon_nr
		{
			get
			{
				return this._opzichter_persoon_nr;
			}
			set
			{
				if ((this._opzichter_persoon_nr != value))
				{
					this._opzichter_persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bouwbedrijf_nr", DbType="Int")]
		public System.Nullable<int> bouwbedrijf_nr
		{
			get
			{
				return this._bouwbedrijf_nr;
			}
			set
			{
				if ((this._bouwbedrijf_nr != value))
				{
					this._bouwbedrijf_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kopersbegeleidingbedrijf_nr", DbType="Int")]
		public System.Nullable<int> kopersbegeleidingbedrijf_nr
		{
			get
			{
				return this._kopersbegeleidingbedrijf_nr;
			}
			set
			{
				if ((this._kopersbegeleidingbedrijf_nr != value))
				{
					this._kopersbegeleidingbedrijf_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facturatieMEERWERKbedrijf_nr", DbType="Int")]
		public System.Nullable<int> facturatieMEERWERKbedrijf_nr
		{
			get
			{
				return this._facturatieMEERWERKbedrijf_nr;
			}
			set
			{
				if ((this._facturatieMEERWERKbedrijf_nr != value))
				{
					this._facturatieMEERWERKbedrijf_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betalingbedrijf", DbType="Int")]
		public System.Nullable<int> betalingbedrijf
		{
			get
			{
				return this._betalingbedrijf;
			}
			set
			{
				if ((this._betalingbedrijf != value))
				{
					this._betalingbedrijf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tegelshowroom_nr", DbType="Int")]
		public System.Nullable<int> tegelshowroom_nr
		{
			get
			{
				return this._tegelshowroom_nr;
			}
			set
			{
				if ((this._tegelshowroom_nr != value))
				{
					this._tegelshowroom_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanitairshowroom_nr", DbType="Int")]
		public System.Nullable<int> sanitairshowroom_nr
		{
			get
			{
				return this._sanitairshowroom_nr;
			}
			set
			{
				if ((this._sanitairshowroom_nr != value))
				{
					this._sanitairshowroom_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keukenshowroom_nr", DbType="Int")]
		public System.Nullable<int> keukenshowroom_nr
		{
			get
			{
				return this._keukenshowroom_nr;
			}
			set
			{
				if ((this._keukenshowroom_nr != value))
				{
					this._keukenshowroom_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectontwikkelaar_nr", DbType="Int")]
		public System.Nullable<int> projectontwikkelaar_nr
		{
			get
			{
				return this._projectontwikkelaar_nr;
			}
			set
			{
				if ((this._projectontwikkelaar_nr != value))
				{
					this._projectontwikkelaar_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[showroom-PARTNER-NR]", Storage="_showroom_PARTNER_NR", DbType="Int")]
		public System.Nullable<int> showroom_PARTNER_NR
		{
			get
			{
				return this._showroom_PARTNER_NR;
			}
			set
			{
				if ((this._showroom_PARTNER_NR != value))
				{
					this._showroom_PARTNER_NR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[leverancier-HOEKPROFIELEN]", Storage="_leverancier_HOEKPROFIELEN", DbType="Int")]
		public System.Nullable<int> leverancier_HOEKPROFIELEN
		{
			get
			{
				return this._leverancier_HOEKPROFIELEN;
			}
			set
			{
				if ((this._leverancier_HOEKPROFIELEN != value))
				{
					this._leverancier_HOEKPROFIELEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[leverancier-STANDAARD]", Storage="_leverancier_STANDAARD", DbType="Int")]
		public System.Nullable<int> leverancier_STANDAARD
		{
			get
			{
				return this._leverancier_STANDAARD;
			}
			set
			{
				if ((this._leverancier_STANDAARD != value))
				{
					this._leverancier_STANDAARD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[opdrachtgever-bestelling-partner-nr]", Storage="_opdrachtgever_bestelling_partner_nr", DbType="Int")]
		public System.Nullable<int> opdrachtgever_bestelling_partner_nr
		{
			get
			{
				return this._opdrachtgever_bestelling_partner_nr;
			}
			set
			{
				if ((this._opdrachtgever_bestelling_partner_nr != value))
				{
					this._opdrachtgever_bestelling_partner_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verpakkingstoeslagUpgrade", DbType="Bit")]
		public System.Nullable<bool> verpakkingstoeslagUpgrade
		{
			get
			{
				return this._verpakkingstoeslagUpgrade;
			}
			set
			{
				if ((this._verpakkingstoeslagUpgrade != value))
				{
					this._verpakkingstoeslagUpgrade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectNRadminZeebregts", DbType="NVarChar(50)")]
		public string projectNRadminZeebregts
		{
			get
			{
				return this._projectNRadminZeebregts;
			}
			set
			{
				if ((this._projectNRadminZeebregts != value))
				{
					this._projectNRadminZeebregts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_bouw", DbType="Int")]
		public System.Nullable<int> adres_id_bouw
		{
			get
			{
				return this._adres_id_bouw;
			}
			set
			{
				if ((this._adres_id_bouw != value))
				{
					this._adres_id_bouw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_factuur", DbType="Int")]
		public System.Nullable<int> adres_id_factuur
		{
			get
			{
				return this._adres_id_factuur;
			}
			set
			{
				if ((this._adres_id_factuur != value))
				{
					this._adres_id_factuur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_1", DbType="NVarChar(50)")]
		public string telefoon_nr_1
		{
			get
			{
				return this._telefoon_nr_1;
			}
			set
			{
				if ((this._telefoon_nr_1 != value))
				{
					this._telefoon_nr_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_2", DbType="NVarChar(50)")]
		public string telefoon_nr_2
		{
			get
			{
				return this._telefoon_nr_2;
			}
			set
			{
				if ((this._telefoon_nr_2 != value))
				{
					this._telefoon_nr_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_3", DbType="NVarChar(50)")]
		public string telefoon_nr_3
		{
			get
			{
				return this._telefoon_nr_3;
			}
			set
			{
				if ((this._telefoon_nr_3 != value))
				{
					this._telefoon_nr_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_settings", DbType="NVarChar(10)")]
		public string telefoon_nr_settings
		{
			get
			{
				return this._telefoon_nr_settings;
			}
			set
			{
				if ((this._telefoon_nr_settings != value))
				{
					this._telefoon_nr_settings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_btw", DbType="Decimal(5,2) NOT NULL")]
		public decimal btw
		{
			get
			{
				return this._btw;
			}
			set
			{
				if ((this._btw != value))
				{
					this._btw = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
