#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GebruikersMonitor
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="zeebregtsdb")]
	public partial class Linq2handelingenLogDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertgebruikers_handelingen(gebruikers_handelingen instance);
    partial void Updategebruikers_handelingen(gebruikers_handelingen instance);
    partial void Deletegebruikers_handelingen(gebruikers_handelingen instance);
    #endregion
		
		public Linq2handelingenLogDataContext() : 
				base(global::GebruikersMonitor.Properties.Settings.Default.zeebregtsdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2handelingenLogDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2handelingenLogDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2handelingenLogDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2handelingenLogDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<log_handeling_gebruiker> log_handeling_gebruikers
		{
			get
			{
				return this.GetTable<log_handeling_gebruiker>();
			}
		}
		
		public System.Data.Linq.Table<gebruikers_handelingen> gebruikers_handelingens
		{
			get
			{
				return this.GetTable<gebruikers_handelingen>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.handeling_log_project")]
		public ISingleResult<handeling_log_projectResult> handeling_log_project()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<handeling_log_projectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.handeling_log_bedrijf")]
		public ISingleResult<handeling_log_bedrijfResult> handeling_log_bedrijf()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<handeling_log_bedrijfResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.handeling_log_contact")]
		public ISingleResult<handeling_log_contactResult> handeling_log_contact()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<handeling_log_contactResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.handeling_log_algemeen")]
		public ISingleResult<handeling_log_algemeenResult> handeling_log_algemeen()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<handeling_log_algemeenResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.log_handeling_gebruiker")]
	public partial class log_handeling_gebruiker
	{
		
		private int _log_id;
		
		private System.Nullable<int> _user_level;
		
		private string _gebruiker;
		
		private System.Nullable<int> _record_id;
		
		private System.Nullable<int> _record_type;
		
		private System.Nullable<int> _handeling_nr;
		
		private System.Nullable<System.DateTime> _timestamp;
		
		public log_handeling_gebruiker()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this._log_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_level", DbType="Int")]
		public System.Nullable<int> user_level
		{
			get
			{
				return this._user_level;
			}
			set
			{
				if ((this._user_level != value))
				{
					this._user_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gebruiker", DbType="NVarChar(50)")]
		public string gebruiker
		{
			get
			{
				return this._gebruiker;
			}
			set
			{
				if ((this._gebruiker != value))
				{
					this._gebruiker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_id", DbType="Int")]
		public System.Nullable<int> record_id
		{
			get
			{
				return this._record_id;
			}
			set
			{
				if ((this._record_id != value))
				{
					this._record_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_type", DbType="Int")]
		public System.Nullable<int> record_type
		{
			get
			{
				return this._record_type;
			}
			set
			{
				if ((this._record_type != value))
				{
					this._record_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handeling_nr", DbType="Int")]
		public System.Nullable<int> handeling_nr
		{
			get
			{
				return this._handeling_nr;
			}
			set
			{
				if ((this._handeling_nr != value))
				{
					this._handeling_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this._timestamp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gebruikers_handelingen")]
	public partial class gebruikers_handelingen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _handeling_nr;
		
		private string _handeling_omschrijving;
		
		private string _Categorie;
		
		private System.Nullable<int> _Sort_order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhandeling_nrChanging(int value);
    partial void Onhandeling_nrChanged();
    partial void Onhandeling_omschrijvingChanging(string value);
    partial void Onhandeling_omschrijvingChanged();
    partial void OnCategorieChanging(string value);
    partial void OnCategorieChanged();
    partial void OnSort_orderChanging(System.Nullable<int> value);
    partial void OnSort_orderChanged();
    #endregion
		
		public gebruikers_handelingen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handeling_nr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int handeling_nr
		{
			get
			{
				return this._handeling_nr;
			}
			set
			{
				if ((this._handeling_nr != value))
				{
					this.Onhandeling_nrChanging(value);
					this.SendPropertyChanging();
					this._handeling_nr = value;
					this.SendPropertyChanged("handeling_nr");
					this.Onhandeling_nrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handeling_omschrijving", DbType="NVarChar(100)")]
		public string handeling_omschrijving
		{
			get
			{
				return this._handeling_omschrijving;
			}
			set
			{
				if ((this._handeling_omschrijving != value))
				{
					this.Onhandeling_omschrijvingChanging(value);
					this.SendPropertyChanging();
					this._handeling_omschrijving = value;
					this.SendPropertyChanged("handeling_omschrijving");
					this.Onhandeling_omschrijvingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categorie", DbType="NVarChar(50)")]
		public string Categorie
		{
			get
			{
				return this._Categorie;
			}
			set
			{
				if ((this._Categorie != value))
				{
					this.OnCategorieChanging(value);
					this.SendPropertyChanging();
					this._Categorie = value;
					this.SendPropertyChanged("Categorie");
					this.OnCategorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort_order", DbType="Int")]
		public System.Nullable<int> Sort_order
		{
			get
			{
				return this._Sort_order;
			}
			set
			{
				if ((this._Sort_order != value))
				{
					this.OnSort_orderChanging(value);
					this.SendPropertyChanging();
					this._Sort_order = value;
					this.SendPropertyChanged("Sort_order");
					this.OnSort_orderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class handeling_log_projectResult
	{
		
		private string _gebruiker;
		
		private System.Nullable<int> _Listview_normaal_open_project;
		
		private System.Nullable<int> _Listview_normaal_nieuw_project;
		
		private System.Nullable<int> _Record_gewijzigd;
		
		private System.Nullable<int> _Copy2Clipboard_NAW_gebruikt;
		
		private System.Nullable<int> _Website_geopend;
		
		private System.Nullable<int> _Project_verwijderd;
		
		private System.Nullable<int> _nieuwe_projecten_ingevoer;
		
		private System.Nullable<int> _Dubbele_invoer_staat_in_lijst;
		
		private System.Nullable<int> _Dubbele_invoer_staat_niet_in_lijst;
		
		private System.Nullable<int> _Listview_advanced_filter_gebruikt;
		
		private System.Nullable<int> @__1e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__2e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__3e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__4e_zoekregel_gebruikt;
		
		public handeling_log_projectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gebruiker", DbType="NVarChar(50)")]
		public string gebruiker
		{
			get
			{
				return this._gebruiker;
			}
			set
			{
				if ((this._gebruiker != value))
				{
					this._gebruiker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview normaal open project]", Storage="_Listview_normaal_open_project", DbType="Int")]
		public System.Nullable<int> Listview_normaal_open_project
		{
			get
			{
				return this._Listview_normaal_open_project;
			}
			set
			{
				if ((this._Listview_normaal_open_project != value))
				{
					this._Listview_normaal_open_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview normaal nieuw project]", Storage="_Listview_normaal_nieuw_project", DbType="Int")]
		public System.Nullable<int> Listview_normaal_nieuw_project
		{
			get
			{
				return this._Listview_normaal_nieuw_project;
			}
			set
			{
				if ((this._Listview_normaal_nieuw_project != value))
				{
					this._Listview_normaal_nieuw_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Record gewijzigd]", Storage="_Record_gewijzigd", DbType="Int")]
		public System.Nullable<int> Record_gewijzigd
		{
			get
			{
				return this._Record_gewijzigd;
			}
			set
			{
				if ((this._Record_gewijzigd != value))
				{
					this._Record_gewijzigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Copy2Clipboard NAW gebruikt]", Storage="_Copy2Clipboard_NAW_gebruikt", DbType="Int")]
		public System.Nullable<int> Copy2Clipboard_NAW_gebruikt
		{
			get
			{
				return this._Copy2Clipboard_NAW_gebruikt;
			}
			set
			{
				if ((this._Copy2Clipboard_NAW_gebruikt != value))
				{
					this._Copy2Clipboard_NAW_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Website geopend]", Storage="_Website_geopend", DbType="Int")]
		public System.Nullable<int> Website_geopend
		{
			get
			{
				return this._Website_geopend;
			}
			set
			{
				if ((this._Website_geopend != value))
				{
					this._Website_geopend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Project verwijderd]", Storage="_Project_verwijderd", DbType="Int")]
		public System.Nullable<int> Project_verwijderd
		{
			get
			{
				return this._Project_verwijderd;
			}
			set
			{
				if ((this._Project_verwijderd != value))
				{
					this._Project_verwijderd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[nieuwe projecten ingevoer]", Storage="_nieuwe_projecten_ingevoer", DbType="Int")]
		public System.Nullable<int> nieuwe_projecten_ingevoer
		{
			get
			{
				return this._nieuwe_projecten_ingevoer;
			}
			set
			{
				if ((this._nieuwe_projecten_ingevoer != value))
				{
					this._nieuwe_projecten_ingevoer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbele invoer staat in lijst]", Storage="_Dubbele_invoer_staat_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbele_invoer_staat_in_lijst
		{
			get
			{
				return this._Dubbele_invoer_staat_in_lijst;
			}
			set
			{
				if ((this._Dubbele_invoer_staat_in_lijst != value))
				{
					this._Dubbele_invoer_staat_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbele invoer staat niet in lijst]", Storage="_Dubbele_invoer_staat_niet_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbele_invoer_staat_niet_in_lijst
		{
			get
			{
				return this._Dubbele_invoer_staat_niet_in_lijst;
			}
			set
			{
				if ((this._Dubbele_invoer_staat_niet_in_lijst != value))
				{
					this._Dubbele_invoer_staat_niet_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview advanced filter gebruikt]", Storage="_Listview_advanced_filter_gebruikt", DbType="Int")]
		public System.Nullable<int> Listview_advanced_filter_gebruikt
		{
			get
			{
				return this._Listview_advanced_filter_gebruikt;
			}
			set
			{
				if ((this._Listview_advanced_filter_gebruikt != value))
				{
					this._Listview_advanced_filter_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1e zoekregel gebruikt]", Storage="__1e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _1e_zoekregel_gebruikt
		{
			get
			{
				return this.@__1e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__1e_zoekregel_gebruikt != value))
				{
					this.@__1e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2e zoekregel gebruikt]", Storage="__2e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _2e_zoekregel_gebruikt
		{
			get
			{
				return this.@__2e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__2e_zoekregel_gebruikt != value))
				{
					this.@__2e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3e zoekregel gebruikt]", Storage="__3e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _3e_zoekregel_gebruikt
		{
			get
			{
				return this.@__3e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__3e_zoekregel_gebruikt != value))
				{
					this.@__3e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4e zoekregel gebruikt]", Storage="__4e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _4e_zoekregel_gebruikt
		{
			get
			{
				return this.@__4e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__4e_zoekregel_gebruikt != value))
				{
					this.@__4e_zoekregel_gebruikt = value;
				}
			}
		}
	}
	
	public partial class handeling_log_bedrijfResult
	{
		
		private string _gebruiker;
		
		private System.Nullable<int> _Listview_normaal_open_bedrijf;
		
		private System.Nullable<int> _Listview_normaal_nieuw_bedrijf;
		
		private System.Nullable<int> _Bedrijf_gewijzigd;
		
		private System.Nullable<int> _Copy2Clipboard_NAW_gebruikt;
		
		private System.Nullable<int> _Website_geopend;
		
		private System.Nullable<int> _E_mail_geopend;
		
		private System.Nullable<int> _Bedrijf_verwijderd;
		
		private System.Nullable<int> _Verwijderen_niet_mogelijk_terug_naar_lijst;
		
		private System.Nullable<int> _Verwijderen_niet_mogelijk__vervangen_en_verwijderd;
		
		private System.Nullable<int> _Nieuw_bedrijf_via_rode_route_project;
		
		private System.Nullable<int> _Bedrijf_geselecteerd_via_rode_route_project;
		
		private System.Nullable<int> _Bedrijf_bekeken_via_groene_route_project;
		
		private System.Nullable<int> _Bedrijf_gewijzigd_via_groene_route_project;
		
		private System.Nullable<int> _Nieuw_bedrijf_via_rode_route_contact;
		
		private System.Nullable<int> _Bedrijf_geselecteerd_via_rode_route_contact;
		
		private System.Nullable<int> _Bedrijf_bekeken_via_groene_route_contact;
		
		private System.Nullable<int> _Bedrijf_gewijzigd_via_groene_route_contact;
		
		private System.Nullable<int> _Nieuw_bedrijf_ingevoerd;
		
		private System.Nullable<int> _Dubbele_invoer_wel_in_lijst;
		
		private System.Nullable<int> _Dubbele_invoer_niet_in_lijst;
		
		private System.Nullable<int> _Listview_advanced_filter_gebruikt;
		
		private System.Nullable<int> @__1e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__2e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__3e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__4e_zoekregel_gebruikt;
		
		public handeling_log_bedrijfResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gebruiker", DbType="NVarChar(50)")]
		public string gebruiker
		{
			get
			{
				return this._gebruiker;
			}
			set
			{
				if ((this._gebruiker != value))
				{
					this._gebruiker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview normaal open bedrijf]", Storage="_Listview_normaal_open_bedrijf", DbType="Int")]
		public System.Nullable<int> Listview_normaal_open_bedrijf
		{
			get
			{
				return this._Listview_normaal_open_bedrijf;
			}
			set
			{
				if ((this._Listview_normaal_open_bedrijf != value))
				{
					this._Listview_normaal_open_bedrijf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview normaal nieuw bedrijf]", Storage="_Listview_normaal_nieuw_bedrijf", DbType="Int")]
		public System.Nullable<int> Listview_normaal_nieuw_bedrijf
		{
			get
			{
				return this._Listview_normaal_nieuw_bedrijf;
			}
			set
			{
				if ((this._Listview_normaal_nieuw_bedrijf != value))
				{
					this._Listview_normaal_nieuw_bedrijf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf gewijzigd]", Storage="_Bedrijf_gewijzigd", DbType="Int")]
		public System.Nullable<int> Bedrijf_gewijzigd
		{
			get
			{
				return this._Bedrijf_gewijzigd;
			}
			set
			{
				if ((this._Bedrijf_gewijzigd != value))
				{
					this._Bedrijf_gewijzigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Copy2Clipboard NAW gebruikt]", Storage="_Copy2Clipboard_NAW_gebruikt", DbType="Int")]
		public System.Nullable<int> Copy2Clipboard_NAW_gebruikt
		{
			get
			{
				return this._Copy2Clipboard_NAW_gebruikt;
			}
			set
			{
				if ((this._Copy2Clipboard_NAW_gebruikt != value))
				{
					this._Copy2Clipboard_NAW_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Website geopend]", Storage="_Website_geopend", DbType="Int")]
		public System.Nullable<int> Website_geopend
		{
			get
			{
				return this._Website_geopend;
			}
			set
			{
				if ((this._Website_geopend != value))
				{
					this._Website_geopend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail geopend]", Storage="_E_mail_geopend", DbType="Int")]
		public System.Nullable<int> E_mail_geopend
		{
			get
			{
				return this._E_mail_geopend;
			}
			set
			{
				if ((this._E_mail_geopend != value))
				{
					this._E_mail_geopend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf verwijderd]", Storage="_Bedrijf_verwijderd", DbType="Int")]
		public System.Nullable<int> Bedrijf_verwijderd
		{
			get
			{
				return this._Bedrijf_verwijderd;
			}
			set
			{
				if ((this._Bedrijf_verwijderd != value))
				{
					this._Bedrijf_verwijderd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Verwijderen niet mogelijk terug naar lijst]", Storage="_Verwijderen_niet_mogelijk_terug_naar_lijst", DbType="Int")]
		public System.Nullable<int> Verwijderen_niet_mogelijk_terug_naar_lijst
		{
			get
			{
				return this._Verwijderen_niet_mogelijk_terug_naar_lijst;
			}
			set
			{
				if ((this._Verwijderen_niet_mogelijk_terug_naar_lijst != value))
				{
					this._Verwijderen_niet_mogelijk_terug_naar_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Verwijderen niet mogelijk, vervangen en verwijderd]", Storage="_Verwijderen_niet_mogelijk__vervangen_en_verwijderd", DbType="Int")]
		public System.Nullable<int> Verwijderen_niet_mogelijk__vervangen_en_verwijderd
		{
			get
			{
				return this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd;
			}
			set
			{
				if ((this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd != value))
				{
					this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw bedrijf via rode route project]", Storage="_Nieuw_bedrijf_via_rode_route_project", DbType="Int")]
		public System.Nullable<int> Nieuw_bedrijf_via_rode_route_project
		{
			get
			{
				return this._Nieuw_bedrijf_via_rode_route_project;
			}
			set
			{
				if ((this._Nieuw_bedrijf_via_rode_route_project != value))
				{
					this._Nieuw_bedrijf_via_rode_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf geselecteerd via rode route project]", Storage="_Bedrijf_geselecteerd_via_rode_route_project", DbType="Int")]
		public System.Nullable<int> Bedrijf_geselecteerd_via_rode_route_project
		{
			get
			{
				return this._Bedrijf_geselecteerd_via_rode_route_project;
			}
			set
			{
				if ((this._Bedrijf_geselecteerd_via_rode_route_project != value))
				{
					this._Bedrijf_geselecteerd_via_rode_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf bekeken via groene route project]", Storage="_Bedrijf_bekeken_via_groene_route_project", DbType="Int")]
		public System.Nullable<int> Bedrijf_bekeken_via_groene_route_project
		{
			get
			{
				return this._Bedrijf_bekeken_via_groene_route_project;
			}
			set
			{
				if ((this._Bedrijf_bekeken_via_groene_route_project != value))
				{
					this._Bedrijf_bekeken_via_groene_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf gewijzigd via groene route project]", Storage="_Bedrijf_gewijzigd_via_groene_route_project", DbType="Int")]
		public System.Nullable<int> Bedrijf_gewijzigd_via_groene_route_project
		{
			get
			{
				return this._Bedrijf_gewijzigd_via_groene_route_project;
			}
			set
			{
				if ((this._Bedrijf_gewijzigd_via_groene_route_project != value))
				{
					this._Bedrijf_gewijzigd_via_groene_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw bedrijf via rode route contact]", Storage="_Nieuw_bedrijf_via_rode_route_contact", DbType="Int")]
		public System.Nullable<int> Nieuw_bedrijf_via_rode_route_contact
		{
			get
			{
				return this._Nieuw_bedrijf_via_rode_route_contact;
			}
			set
			{
				if ((this._Nieuw_bedrijf_via_rode_route_contact != value))
				{
					this._Nieuw_bedrijf_via_rode_route_contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf geselecteerd via rode route contact]", Storage="_Bedrijf_geselecteerd_via_rode_route_contact", DbType="Int")]
		public System.Nullable<int> Bedrijf_geselecteerd_via_rode_route_contact
		{
			get
			{
				return this._Bedrijf_geselecteerd_via_rode_route_contact;
			}
			set
			{
				if ((this._Bedrijf_geselecteerd_via_rode_route_contact != value))
				{
					this._Bedrijf_geselecteerd_via_rode_route_contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf bekeken via groene route contact]", Storage="_Bedrijf_bekeken_via_groene_route_contact", DbType="Int")]
		public System.Nullable<int> Bedrijf_bekeken_via_groene_route_contact
		{
			get
			{
				return this._Bedrijf_bekeken_via_groene_route_contact;
			}
			set
			{
				if ((this._Bedrijf_bekeken_via_groene_route_contact != value))
				{
					this._Bedrijf_bekeken_via_groene_route_contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bedrijf gewijzigd via groene route contact]", Storage="_Bedrijf_gewijzigd_via_groene_route_contact", DbType="Int")]
		public System.Nullable<int> Bedrijf_gewijzigd_via_groene_route_contact
		{
			get
			{
				return this._Bedrijf_gewijzigd_via_groene_route_contact;
			}
			set
			{
				if ((this._Bedrijf_gewijzigd_via_groene_route_contact != value))
				{
					this._Bedrijf_gewijzigd_via_groene_route_contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw bedrijf ingevoerd]", Storage="_Nieuw_bedrijf_ingevoerd", DbType="Int")]
		public System.Nullable<int> Nieuw_bedrijf_ingevoerd
		{
			get
			{
				return this._Nieuw_bedrijf_ingevoerd;
			}
			set
			{
				if ((this._Nieuw_bedrijf_ingevoerd != value))
				{
					this._Nieuw_bedrijf_ingevoerd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbele invoer wel in lijst]", Storage="_Dubbele_invoer_wel_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbele_invoer_wel_in_lijst
		{
			get
			{
				return this._Dubbele_invoer_wel_in_lijst;
			}
			set
			{
				if ((this._Dubbele_invoer_wel_in_lijst != value))
				{
					this._Dubbele_invoer_wel_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbele invoer niet in lijst]", Storage="_Dubbele_invoer_niet_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbele_invoer_niet_in_lijst
		{
			get
			{
				return this._Dubbele_invoer_niet_in_lijst;
			}
			set
			{
				if ((this._Dubbele_invoer_niet_in_lijst != value))
				{
					this._Dubbele_invoer_niet_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview advanced filter gebruikt]", Storage="_Listview_advanced_filter_gebruikt", DbType="Int")]
		public System.Nullable<int> Listview_advanced_filter_gebruikt
		{
			get
			{
				return this._Listview_advanced_filter_gebruikt;
			}
			set
			{
				if ((this._Listview_advanced_filter_gebruikt != value))
				{
					this._Listview_advanced_filter_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1e zoekregel gebruikt]", Storage="__1e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _1e_zoekregel_gebruikt
		{
			get
			{
				return this.@__1e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__1e_zoekregel_gebruikt != value))
				{
					this.@__1e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2e zoekregel gebruikt]", Storage="__2e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _2e_zoekregel_gebruikt
		{
			get
			{
				return this.@__2e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__2e_zoekregel_gebruikt != value))
				{
					this.@__2e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3e zoekregel gebruikt]", Storage="__3e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _3e_zoekregel_gebruikt
		{
			get
			{
				return this.@__3e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__3e_zoekregel_gebruikt != value))
				{
					this.@__3e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4e zoekregel gebruikt]", Storage="__4e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _4e_zoekregel_gebruikt
		{
			get
			{
				return this.@__4e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__4e_zoekregel_gebruikt != value))
				{
					this.@__4e_zoekregel_gebruikt = value;
				}
			}
		}
	}
	
	public partial class handeling_log_contactResult
	{
		
		private string _gebruiker;
		
		private System.Nullable<int> _Listview_normaal_geselecteerd;
		
		private System.Nullable<int> _Nieuw_record_toegevoegd;
		
		private System.Nullable<int> _Contact_gewijzigd;
		
		private System.Nullable<int> _Copy2Clipboard_NAW;
		
		private System.Nullable<int> _Copy2Clipboard_post;
		
		private System.Nullable<int> _Copy2Clipboard_bezoek;
		
		private System.Nullable<int> _E_mail_geopend;
		
		private System.Nullable<int> _Verwijderd;
		
		private System.Nullable<int> _Verwijderen_niet_mogelijk_terug_naar_leesstand;
		
		private System.Nullable<int> _Verwijderen_niet_mogelijk__vervangen_en_verwijderd;
		
		private System.Nullable<int> _Nieuw_record_via_rode_route_project;
		
		private System.Nullable<int> _Contact_geselecteerd_via_rode_route_project;
		
		private System.Nullable<int> _Contact_bekeken_via_groene_route_project;
		
		private System.Nullable<int> _Contact_gewijzigd_via_groene_route_project;
		
		private System.Nullable<int> _Nieuw_contact_toegevoegd;
		
		private System.Nullable<int> _Dubbel_invoer_staat_in_lijst;
		
		private System.Nullable<int> _Dubbel_invoer_staat_niet_in_lijst;
		
		private System.Nullable<int> _Listview_advanced_filter_gebruikt;
		
		private System.Nullable<int> @__1e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__2e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__3e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__4e_zoekregel_gebruikt;
		
		public handeling_log_contactResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gebruiker", DbType="NVarChar(50)")]
		public string gebruiker
		{
			get
			{
				return this._gebruiker;
			}
			set
			{
				if ((this._gebruiker != value))
				{
					this._gebruiker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview normaal geselecteerd]", Storage="_Listview_normaal_geselecteerd", DbType="Int")]
		public System.Nullable<int> Listview_normaal_geselecteerd
		{
			get
			{
				return this._Listview_normaal_geselecteerd;
			}
			set
			{
				if ((this._Listview_normaal_geselecteerd != value))
				{
					this._Listview_normaal_geselecteerd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw record toegevoegd]", Storage="_Nieuw_record_toegevoegd", DbType="Int")]
		public System.Nullable<int> Nieuw_record_toegevoegd
		{
			get
			{
				return this._Nieuw_record_toegevoegd;
			}
			set
			{
				if ((this._Nieuw_record_toegevoegd != value))
				{
					this._Nieuw_record_toegevoegd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact gewijzigd]", Storage="_Contact_gewijzigd", DbType="Int")]
		public System.Nullable<int> Contact_gewijzigd
		{
			get
			{
				return this._Contact_gewijzigd;
			}
			set
			{
				if ((this._Contact_gewijzigd != value))
				{
					this._Contact_gewijzigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Copy2Clipboard NAW]", Storage="_Copy2Clipboard_NAW", DbType="Int")]
		public System.Nullable<int> Copy2Clipboard_NAW
		{
			get
			{
				return this._Copy2Clipboard_NAW;
			}
			set
			{
				if ((this._Copy2Clipboard_NAW != value))
				{
					this._Copy2Clipboard_NAW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Copy2Clipboard post]", Storage="_Copy2Clipboard_post", DbType="Int")]
		public System.Nullable<int> Copy2Clipboard_post
		{
			get
			{
				return this._Copy2Clipboard_post;
			}
			set
			{
				if ((this._Copy2Clipboard_post != value))
				{
					this._Copy2Clipboard_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Copy2Clipboard bezoek]", Storage="_Copy2Clipboard_bezoek", DbType="Int")]
		public System.Nullable<int> Copy2Clipboard_bezoek
		{
			get
			{
				return this._Copy2Clipboard_bezoek;
			}
			set
			{
				if ((this._Copy2Clipboard_bezoek != value))
				{
					this._Copy2Clipboard_bezoek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail geopend]", Storage="_E_mail_geopend", DbType="Int")]
		public System.Nullable<int> E_mail_geopend
		{
			get
			{
				return this._E_mail_geopend;
			}
			set
			{
				if ((this._E_mail_geopend != value))
				{
					this._E_mail_geopend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verwijderd", DbType="Int")]
		public System.Nullable<int> Verwijderd
		{
			get
			{
				return this._Verwijderd;
			}
			set
			{
				if ((this._Verwijderd != value))
				{
					this._Verwijderd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Verwijderen niet mogelijk terug naar leesstand]", Storage="_Verwijderen_niet_mogelijk_terug_naar_leesstand", DbType="Int")]
		public System.Nullable<int> Verwijderen_niet_mogelijk_terug_naar_leesstand
		{
			get
			{
				return this._Verwijderen_niet_mogelijk_terug_naar_leesstand;
			}
			set
			{
				if ((this._Verwijderen_niet_mogelijk_terug_naar_leesstand != value))
				{
					this._Verwijderen_niet_mogelijk_terug_naar_leesstand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Verwijderen niet mogelijk, vervangen en verwijderd]", Storage="_Verwijderen_niet_mogelijk__vervangen_en_verwijderd", DbType="Int")]
		public System.Nullable<int> Verwijderen_niet_mogelijk__vervangen_en_verwijderd
		{
			get
			{
				return this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd;
			}
			set
			{
				if ((this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd != value))
				{
					this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw record via rode route project]", Storage="_Nieuw_record_via_rode_route_project", DbType="Int")]
		public System.Nullable<int> Nieuw_record_via_rode_route_project
		{
			get
			{
				return this._Nieuw_record_via_rode_route_project;
			}
			set
			{
				if ((this._Nieuw_record_via_rode_route_project != value))
				{
					this._Nieuw_record_via_rode_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact geselecteerd via rode route project]", Storage="_Contact_geselecteerd_via_rode_route_project", DbType="Int")]
		public System.Nullable<int> Contact_geselecteerd_via_rode_route_project
		{
			get
			{
				return this._Contact_geselecteerd_via_rode_route_project;
			}
			set
			{
				if ((this._Contact_geselecteerd_via_rode_route_project != value))
				{
					this._Contact_geselecteerd_via_rode_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact bekeken via groene route project]", Storage="_Contact_bekeken_via_groene_route_project", DbType="Int")]
		public System.Nullable<int> Contact_bekeken_via_groene_route_project
		{
			get
			{
				return this._Contact_bekeken_via_groene_route_project;
			}
			set
			{
				if ((this._Contact_bekeken_via_groene_route_project != value))
				{
					this._Contact_bekeken_via_groene_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact gewijzigd via groene route project]", Storage="_Contact_gewijzigd_via_groene_route_project", DbType="Int")]
		public System.Nullable<int> Contact_gewijzigd_via_groene_route_project
		{
			get
			{
				return this._Contact_gewijzigd_via_groene_route_project;
			}
			set
			{
				if ((this._Contact_gewijzigd_via_groene_route_project != value))
				{
					this._Contact_gewijzigd_via_groene_route_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw contact toegevoegd]", Storage="_Nieuw_contact_toegevoegd", DbType="Int")]
		public System.Nullable<int> Nieuw_contact_toegevoegd
		{
			get
			{
				return this._Nieuw_contact_toegevoegd;
			}
			set
			{
				if ((this._Nieuw_contact_toegevoegd != value))
				{
					this._Nieuw_contact_toegevoegd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbel invoer staat in lijst]", Storage="_Dubbel_invoer_staat_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbel_invoer_staat_in_lijst
		{
			get
			{
				return this._Dubbel_invoer_staat_in_lijst;
			}
			set
			{
				if ((this._Dubbel_invoer_staat_in_lijst != value))
				{
					this._Dubbel_invoer_staat_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbel invoer staat niet in lijst]", Storage="_Dubbel_invoer_staat_niet_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbel_invoer_staat_niet_in_lijst
		{
			get
			{
				return this._Dubbel_invoer_staat_niet_in_lijst;
			}
			set
			{
				if ((this._Dubbel_invoer_staat_niet_in_lijst != value))
				{
					this._Dubbel_invoer_staat_niet_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview advanced filter gebruikt]", Storage="_Listview_advanced_filter_gebruikt", DbType="Int")]
		public System.Nullable<int> Listview_advanced_filter_gebruikt
		{
			get
			{
				return this._Listview_advanced_filter_gebruikt;
			}
			set
			{
				if ((this._Listview_advanced_filter_gebruikt != value))
				{
					this._Listview_advanced_filter_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1e zoekregel gebruikt]", Storage="__1e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _1e_zoekregel_gebruikt
		{
			get
			{
				return this.@__1e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__1e_zoekregel_gebruikt != value))
				{
					this.@__1e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2e zoekregel gebruikt]", Storage="__2e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _2e_zoekregel_gebruikt
		{
			get
			{
				return this.@__2e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__2e_zoekregel_gebruikt != value))
				{
					this.@__2e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3e zoekregel gebruikt]", Storage="__3e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _3e_zoekregel_gebruikt
		{
			get
			{
				return this.@__3e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__3e_zoekregel_gebruikt != value))
				{
					this.@__3e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4e zoekregel gebruikt]", Storage="__4e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _4e_zoekregel_gebruikt
		{
			get
			{
				return this.@__4e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__4e_zoekregel_gebruikt != value))
				{
					this.@__4e_zoekregel_gebruikt = value;
				}
			}
		}
	}
	
	public partial class handeling_log_algemeenResult
	{
		
		private string _gebruiker;
		
		private System.Nullable<int> _Listview_normaal_open_record;
		
		private System.Nullable<int> _Nieuw_record_via_normaal_listview;
		
		private System.Nullable<int> _Records_gewijzigd;
		
		private System.Nullable<int> _Copy2Clipboard;
		
		private System.Nullable<int> _E_mail_geopend;
		
		private System.Nullable<int> _Website_geopend;
		
		private System.Nullable<int> _Verwijderd;
		
		private System.Nullable<int> _Verwijderen_niet_mogelijk__terug_naar_leesstand;
		
		private System.Nullable<int> _Verwijderen_niet_mogelijk__vervangen_en_verwijderd;
		
		private System.Nullable<int> _Nieuw_record_via_rode_route;
		
		private System.Nullable<int> _Record_geselecteerd_via_rode_route;
		
		private System.Nullable<int> _Record_bekeken_via_groene_route;
		
		private System.Nullable<int> _Record_gewijzigd_via_groene_route;
		
		private System.Nullable<int> _Nieuw_ingevoerd;
		
		private System.Nullable<int> _Dubbele_invoer__wel_in_lijst;
		
		private System.Nullable<int> _Dubbele_invoer__niet_in_lijst;
		
		private System.Nullable<int> _Advanced_filter_gebruikt;
		
		private System.Nullable<int> @__1e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__2e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__3e_zoekregel_gebruikt;
		
		private System.Nullable<int> @__4e_zoekregel_gebruikt;
		
		public handeling_log_algemeenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gebruiker", DbType="NVarChar(50)")]
		public string gebruiker
		{
			get
			{
				return this._gebruiker;
			}
			set
			{
				if ((this._gebruiker != value))
				{
					this._gebruiker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Listview normaal open record]", Storage="_Listview_normaal_open_record", DbType="Int")]
		public System.Nullable<int> Listview_normaal_open_record
		{
			get
			{
				return this._Listview_normaal_open_record;
			}
			set
			{
				if ((this._Listview_normaal_open_record != value))
				{
					this._Listview_normaal_open_record = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw record via normaal listview]", Storage="_Nieuw_record_via_normaal_listview", DbType="Int")]
		public System.Nullable<int> Nieuw_record_via_normaal_listview
		{
			get
			{
				return this._Nieuw_record_via_normaal_listview;
			}
			set
			{
				if ((this._Nieuw_record_via_normaal_listview != value))
				{
					this._Nieuw_record_via_normaal_listview = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Records gewijzigd]", Storage="_Records_gewijzigd", DbType="Int")]
		public System.Nullable<int> Records_gewijzigd
		{
			get
			{
				return this._Records_gewijzigd;
			}
			set
			{
				if ((this._Records_gewijzigd != value))
				{
					this._Records_gewijzigd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Copy2Clipboard", DbType="Int")]
		public System.Nullable<int> Copy2Clipboard
		{
			get
			{
				return this._Copy2Clipboard;
			}
			set
			{
				if ((this._Copy2Clipboard != value))
				{
					this._Copy2Clipboard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail geopend]", Storage="_E_mail_geopend", DbType="Int")]
		public System.Nullable<int> E_mail_geopend
		{
			get
			{
				return this._E_mail_geopend;
			}
			set
			{
				if ((this._E_mail_geopend != value))
				{
					this._E_mail_geopend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Website geopend]", Storage="_Website_geopend", DbType="Int")]
		public System.Nullable<int> Website_geopend
		{
			get
			{
				return this._Website_geopend;
			}
			set
			{
				if ((this._Website_geopend != value))
				{
					this._Website_geopend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verwijderd", DbType="Int")]
		public System.Nullable<int> Verwijderd
		{
			get
			{
				return this._Verwijderd;
			}
			set
			{
				if ((this._Verwijderd != value))
				{
					this._Verwijderd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Verwijderen niet mogelijk, terug naar leesstand]", Storage="_Verwijderen_niet_mogelijk__terug_naar_leesstand", DbType="Int")]
		public System.Nullable<int> Verwijderen_niet_mogelijk__terug_naar_leesstand
		{
			get
			{
				return this._Verwijderen_niet_mogelijk__terug_naar_leesstand;
			}
			set
			{
				if ((this._Verwijderen_niet_mogelijk__terug_naar_leesstand != value))
				{
					this._Verwijderen_niet_mogelijk__terug_naar_leesstand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Verwijderen niet mogelijk, vervangen en verwijderd]", Storage="_Verwijderen_niet_mogelijk__vervangen_en_verwijderd", DbType="Int")]
		public System.Nullable<int> Verwijderen_niet_mogelijk__vervangen_en_verwijderd
		{
			get
			{
				return this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd;
			}
			set
			{
				if ((this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd != value))
				{
					this._Verwijderen_niet_mogelijk__vervangen_en_verwijderd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw record via rode route]", Storage="_Nieuw_record_via_rode_route", DbType="Int")]
		public System.Nullable<int> Nieuw_record_via_rode_route
		{
			get
			{
				return this._Nieuw_record_via_rode_route;
			}
			set
			{
				if ((this._Nieuw_record_via_rode_route != value))
				{
					this._Nieuw_record_via_rode_route = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Record geselecteerd via rode route]", Storage="_Record_geselecteerd_via_rode_route", DbType="Int")]
		public System.Nullable<int> Record_geselecteerd_via_rode_route
		{
			get
			{
				return this._Record_geselecteerd_via_rode_route;
			}
			set
			{
				if ((this._Record_geselecteerd_via_rode_route != value))
				{
					this._Record_geselecteerd_via_rode_route = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Record bekeken via groene route]", Storage="_Record_bekeken_via_groene_route", DbType="Int")]
		public System.Nullable<int> Record_bekeken_via_groene_route
		{
			get
			{
				return this._Record_bekeken_via_groene_route;
			}
			set
			{
				if ((this._Record_bekeken_via_groene_route != value))
				{
					this._Record_bekeken_via_groene_route = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Record gewijzigd via groene route]", Storage="_Record_gewijzigd_via_groene_route", DbType="Int")]
		public System.Nullable<int> Record_gewijzigd_via_groene_route
		{
			get
			{
				return this._Record_gewijzigd_via_groene_route;
			}
			set
			{
				if ((this._Record_gewijzigd_via_groene_route != value))
				{
					this._Record_gewijzigd_via_groene_route = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nieuw ingevoerd]", Storage="_Nieuw_ingevoerd", DbType="Int")]
		public System.Nullable<int> Nieuw_ingevoerd
		{
			get
			{
				return this._Nieuw_ingevoerd;
			}
			set
			{
				if ((this._Nieuw_ingevoerd != value))
				{
					this._Nieuw_ingevoerd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbele invoer, wel in lijst]", Storage="_Dubbele_invoer__wel_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbele_invoer__wel_in_lijst
		{
			get
			{
				return this._Dubbele_invoer__wel_in_lijst;
			}
			set
			{
				if ((this._Dubbele_invoer__wel_in_lijst != value))
				{
					this._Dubbele_invoer__wel_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dubbele invoer, niet in lijst]", Storage="_Dubbele_invoer__niet_in_lijst", DbType="Int")]
		public System.Nullable<int> Dubbele_invoer__niet_in_lijst
		{
			get
			{
				return this._Dubbele_invoer__niet_in_lijst;
			}
			set
			{
				if ((this._Dubbele_invoer__niet_in_lijst != value))
				{
					this._Dubbele_invoer__niet_in_lijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Advanced filter gebruikt]", Storage="_Advanced_filter_gebruikt", DbType="Int")]
		public System.Nullable<int> Advanced_filter_gebruikt
		{
			get
			{
				return this._Advanced_filter_gebruikt;
			}
			set
			{
				if ((this._Advanced_filter_gebruikt != value))
				{
					this._Advanced_filter_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1e zoekregel gebruikt]", Storage="__1e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _1e_zoekregel_gebruikt
		{
			get
			{
				return this.@__1e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__1e_zoekregel_gebruikt != value))
				{
					this.@__1e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2e zoekregel gebruikt]", Storage="__2e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _2e_zoekregel_gebruikt
		{
			get
			{
				return this.@__2e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__2e_zoekregel_gebruikt != value))
				{
					this.@__2e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3e zoekregel gebruikt]", Storage="__3e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _3e_zoekregel_gebruikt
		{
			get
			{
				return this.@__3e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__3e_zoekregel_gebruikt != value))
				{
					this.@__3e_zoekregel_gebruikt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4e zoekregel gebruikt]", Storage="__4e_zoekregel_gebruikt", DbType="Int")]
		public System.Nullable<int> _4e_zoekregel_gebruikt
		{
			get
			{
				return this.@__4e_zoekregel_gebruikt;
			}
			set
			{
				if ((this.@__4e_zoekregel_gebruikt != value))
				{
					this.@__4e_zoekregel_gebruikt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
