SELECT [persoon_ID]
      ,[persoon_nr]
      ,[bedrijf_nr]
      ,[man]
      ,[voorletters]
      ,[voornaam]
      ,[tussenvoegsel]
      ,[achternaam]
      ,[zamobiel]
      ,[zatelefoonvast]
      ,[zafax]
      ,[zaemail]
      ,[geboortedatum]
      ,[vastevrijedag1]
      ,[vastevrijedag2]
      ,[vastevrijedag3]
      ,[NIETactief]
      ,[adres_id]
  FROM [zeebregtsdb].[dbo].[persoon]
GO

