#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandagenRegistratieDomain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Zeebregtsdb")]
	public partial class dbOriginalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		
		public dbOriginalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbOriginalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbOriginalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbOriginalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MDRadressen> MDRadressens
		{
			get
			{
				return this.GetTable<MDRadressen>();
			}
		}
		
		public System.Data.Linq.Table<MDRproject> MDRprojects
		{
			get
			{
				return this.GetTable<MDRproject>();
			}
		}
		
		public System.Data.Linq.Table<MDRbedrijf> MDRbedrijfs
		{
			get
			{
				return this.GetTable<MDRbedrijf>();
			}
		}
		
		public System.Data.Linq.Table<MDRpersoon> MDRpersoons
		{
			get
			{
				return this.GetTable<MDRpersoon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MDRadressen")]
	public partial class MDRadressen
	{
		
		private int _adres_id;
		
		private string _land;
		
		private string _plaats;
		
		private string _huisnummer_toevoeging;
		
		private string _straat_1;
		
		private string _straat_2;
		
		private System.Nullable<int> _postcode_cijfers;
		
		private string _postcode_letters;
		
		private string _huis_postbus_nummer;
		
		public MDRadressen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id", DbType="Int NOT NULL")]
		public int adres_id
		{
			get
			{
				return this._adres_id;
			}
			set
			{
				if ((this._adres_id != value))
				{
					this._adres_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_land", DbType="NVarChar(50)")]
		public string land
		{
			get
			{
				return this._land;
			}
			set
			{
				if ((this._land != value))
				{
					this._land = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaats", DbType="NVarChar(50)")]
		public string plaats
		{
			get
			{
				return this._plaats;
			}
			set
			{
				if ((this._plaats != value))
				{
					this._plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huisnummer_toevoeging", DbType="NVarChar(50)")]
		public string huisnummer_toevoeging
		{
			get
			{
				return this._huisnummer_toevoeging;
			}
			set
			{
				if ((this._huisnummer_toevoeging != value))
				{
					this._huisnummer_toevoeging = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_straat_1", DbType="NVarChar(100)")]
		public string straat_1
		{
			get
			{
				return this._straat_1;
			}
			set
			{
				if ((this._straat_1 != value))
				{
					this._straat_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_straat_2", DbType="NVarChar(100)")]
		public string straat_2
		{
			get
			{
				return this._straat_2;
			}
			set
			{
				if ((this._straat_2 != value))
				{
					this._straat_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode_cijfers", DbType="Int")]
		public System.Nullable<int> postcode_cijfers
		{
			get
			{
				return this._postcode_cijfers;
			}
			set
			{
				if ((this._postcode_cijfers != value))
				{
					this._postcode_cijfers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode_letters", DbType="NVarChar(2)")]
		public string postcode_letters
		{
			get
			{
				return this._postcode_letters;
			}
			set
			{
				if ((this._postcode_letters != value))
				{
					this._postcode_letters = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huis_postbus_nummer", DbType="NVarChar(50)")]
		public string huis_postbus_nummer
		{
			get
			{
				return this._huis_postbus_nummer;
			}
			set
			{
				if ((this._huis_postbus_nummer != value))
				{
					this._huis_postbus_nummer = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MDRproject")]
	public partial class MDRproject
	{
		
		private int _project_ID;
		
		private System.Nullable<int> _project_NR;
		
		private string _naam_project;
		
		private string _plaats;
		
		private System.Nullable<int> _opdrachtgeverZEEBREGTS_nr;
		
		private System.Nullable<int> _adres_id_bouw;
		
		private string _aannemer_projectnummer;
		
		private string _aannemer_contractnummer;
		
		private string _nacalculatiecode;
		
		private System.Nullable<int> _adres_id_factuur;
		
		public MDRproject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_ID", DbType="Int NOT NULL")]
		public int project_ID
		{
			get
			{
				return this._project_ID;
			}
			set
			{
				if ((this._project_ID != value))
				{
					this._project_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_NR", DbType="Int")]
		public System.Nullable<int> project_NR
		{
			get
			{
				return this._project_NR;
			}
			set
			{
				if ((this._project_NR != value))
				{
					this._project_NR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam_project", DbType="NVarChar(100)")]
		public string naam_project
		{
			get
			{
				return this._naam_project;
			}
			set
			{
				if ((this._naam_project != value))
				{
					this._naam_project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaats", DbType="NVarChar(50)")]
		public string plaats
		{
			get
			{
				return this._plaats;
			}
			set
			{
				if ((this._plaats != value))
				{
					this._plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opdrachtgeverZEEBREGTS_nr", DbType="Int")]
		public System.Nullable<int> opdrachtgeverZEEBREGTS_nr
		{
			get
			{
				return this._opdrachtgeverZEEBREGTS_nr;
			}
			set
			{
				if ((this._opdrachtgeverZEEBREGTS_nr != value))
				{
					this._opdrachtgeverZEEBREGTS_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_bouw", DbType="Int")]
		public System.Nullable<int> adres_id_bouw
		{
			get
			{
				return this._adres_id_bouw;
			}
			set
			{
				if ((this._adres_id_bouw != value))
				{
					this._adres_id_bouw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aannemer_projectnummer", DbType="NVarChar(50)")]
		public string aannemer_projectnummer
		{
			get
			{
				return this._aannemer_projectnummer;
			}
			set
			{
				if ((this._aannemer_projectnummer != value))
				{
					this._aannemer_projectnummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aannemer_contractnummer", DbType="NVarChar(50)")]
		public string aannemer_contractnummer
		{
			get
			{
				return this._aannemer_contractnummer;
			}
			set
			{
				if ((this._aannemer_contractnummer != value))
				{
					this._aannemer_contractnummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nacalculatiecode", DbType="NVarChar(50)")]
		public string nacalculatiecode
		{
			get
			{
				return this._nacalculatiecode;
			}
			set
			{
				if ((this._nacalculatiecode != value))
				{
					this._nacalculatiecode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_factuur", DbType="Int")]
		public System.Nullable<int> adres_id_factuur
		{
			get
			{
				return this._adres_id_factuur;
			}
			set
			{
				if ((this._adres_id_factuur != value))
				{
					this._adres_id_factuur = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MDRbedrijf")]
	public partial class MDRbedrijf
	{
		
		private int _bedrijf_ID;
		
		private System.Nullable<int> _bedrijf_nr;
		
		private string _naam;
		
		private string _zoeknaam;
		
		private string _plaats;
		
		private System.Nullable<int> _adres_id_bezoek;
		
		private System.Nullable<int> _adres_id_post;
		
		public MDRbedrijf()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijf_ID", DbType="Int NOT NULL")]
		public int bedrijf_ID
		{
			get
			{
				return this._bedrijf_ID;
			}
			set
			{
				if ((this._bedrijf_ID != value))
				{
					this._bedrijf_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijf_nr", DbType="Int")]
		public System.Nullable<int> bedrijf_nr
		{
			get
			{
				return this._bedrijf_nr;
			}
			set
			{
				if ((this._bedrijf_nr != value))
				{
					this._bedrijf_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="NVarChar(150)")]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this._naam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zoeknaam", DbType="NVarChar(52)")]
		public string zoeknaam
		{
			get
			{
				return this._zoeknaam;
			}
			set
			{
				if ((this._zoeknaam != value))
				{
					this._zoeknaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaats", DbType="NVarChar(50)")]
		public string plaats
		{
			get
			{
				return this._plaats;
			}
			set
			{
				if ((this._plaats != value))
				{
					this._plaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_bezoek", DbType="Int")]
		public System.Nullable<int> adres_id_bezoek
		{
			get
			{
				return this._adres_id_bezoek;
			}
			set
			{
				if ((this._adres_id_bezoek != value))
				{
					this._adres_id_bezoek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id_post", DbType="Int")]
		public System.Nullable<int> adres_id_post
		{
			get
			{
				return this._adres_id_post;
			}
			set
			{
				if ((this._adres_id_post != value))
				{
					this._adres_id_post = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MDRpersoon")]
	public partial class MDRpersoon
	{
		
		private int _persoon_ID;
		
		private System.Nullable<int> _persoon_nr;
		
		private string _voorletters;
		
		private string _voornaam;
		
		private string _tussenvoegsel;
		
		private string _achternaam;
		
		private System.Nullable<bool> _man;
		
		private System.Nullable<int> _bedrijf_nr;
		
		private string _telefoon_nr_1;
		
		private string _telefoon_nr_2;
		
		private string _telefoon_nr_3;
		
		private System.Nullable<int> _adres_id;
		
		private System.Nullable<System.DateTime> _geboortedatum;
		
		private string _zaemail;
		
		private string _zamobiel;
		
		private string _zatelefoonvast;
		
		private string _zafax;
		
		public MDRpersoon()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persoon_ID", DbType="Int NOT NULL")]
		public int persoon_ID
		{
			get
			{
				return this._persoon_ID;
			}
			set
			{
				if ((this._persoon_ID != value))
				{
					this._persoon_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persoon_nr", DbType="Int")]
		public System.Nullable<int> persoon_nr
		{
			get
			{
				return this._persoon_nr;
			}
			set
			{
				if ((this._persoon_nr != value))
				{
					this._persoon_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voorletters", DbType="NVarChar(50)")]
		public string voorletters
		{
			get
			{
				return this._voorletters;
			}
			set
			{
				if ((this._voorletters != value))
				{
					this._voorletters = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voornaam", DbType="NVarChar(50)")]
		public string voornaam
		{
			get
			{
				return this._voornaam;
			}
			set
			{
				if ((this._voornaam != value))
				{
					this._voornaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tussenvoegsel", DbType="NVarChar(50)")]
		public string tussenvoegsel
		{
			get
			{
				return this._tussenvoegsel;
			}
			set
			{
				if ((this._tussenvoegsel != value))
				{
					this._tussenvoegsel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achternaam", DbType="NVarChar(50)")]
		public string achternaam
		{
			get
			{
				return this._achternaam;
			}
			set
			{
				if ((this._achternaam != value))
				{
					this._achternaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_man", DbType="Bit")]
		public System.Nullable<bool> man
		{
			get
			{
				return this._man;
			}
			set
			{
				if ((this._man != value))
				{
					this._man = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijf_nr", DbType="Int")]
		public System.Nullable<int> bedrijf_nr
		{
			get
			{
				return this._bedrijf_nr;
			}
			set
			{
				if ((this._bedrijf_nr != value))
				{
					this._bedrijf_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_1", DbType="NVarChar(50)")]
		public string telefoon_nr_1
		{
			get
			{
				return this._telefoon_nr_1;
			}
			set
			{
				if ((this._telefoon_nr_1 != value))
				{
					this._telefoon_nr_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_2", DbType="NVarChar(50)")]
		public string telefoon_nr_2
		{
			get
			{
				return this._telefoon_nr_2;
			}
			set
			{
				if ((this._telefoon_nr_2 != value))
				{
					this._telefoon_nr_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon_nr_3", DbType="NVarChar(50)")]
		public string telefoon_nr_3
		{
			get
			{
				return this._telefoon_nr_3;
			}
			set
			{
				if ((this._telefoon_nr_3 != value))
				{
					this._telefoon_nr_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_id", DbType="Int")]
		public System.Nullable<int> adres_id
		{
			get
			{
				return this._adres_id;
			}
			set
			{
				if ((this._adres_id != value))
				{
					this._adres_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geboortedatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> geboortedatum
		{
			get
			{
				return this._geboortedatum;
			}
			set
			{
				if ((this._geboortedatum != value))
				{
					this._geboortedatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zaemail", DbType="NVarChar(50)")]
		public string zaemail
		{
			get
			{
				return this._zaemail;
			}
			set
			{
				if ((this._zaemail != value))
				{
					this._zaemail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zamobiel", DbType="NVarChar(50)")]
		public string zamobiel
		{
			get
			{
				return this._zamobiel;
			}
			set
			{
				if ((this._zamobiel != value))
				{
					this._zamobiel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zatelefoonvast", DbType="NVarChar(50)")]
		public string zatelefoonvast
		{
			get
			{
				return this._zatelefoonvast;
			}
			set
			{
				if ((this._zatelefoonvast != value))
				{
					this._zatelefoonvast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zafax", DbType="NVarChar(50)")]
		public string zafax
		{
			get
			{
				return this._zafax;
			}
			set
			{
				if ((this._zafax != value))
				{
					this._zafax = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
